return {
  { id = 400, name = 'Landstalker', category = 'Off Road', file = 'veh-400.png' },
  { id = 401, name = 'Bravura', category = 'Saloons', file = 'veh-401.png' },
  { id = 402, name = 'Buffalo', category = 'Sport Vehicles', file = 'veh-402.png' },
  { id = 403, name = 'Linerunner', category = 'Industrial', file = 'veh-403.png' },
  { id = 404, name = 'Perenniel', category = 'Station Wagons', file = 'veh-404.png' },
  { id = 405, name = 'Sentinel', category = 'Saloons', file = 'veh-405.png' },
  { id = 406, name = 'Dumper', category = 'Unique Vehicles', file = 'veh-406.png' },
  { id = 407, name = 'Firetruck', category = 'Public Service', file = 'veh-407.png' },
  { id = 408, name = 'Trashmaster', category = 'Industrial', file = 'veh-408.png' },
  { id = 409, name = 'Stretch', category = 'Unique Vehicles', file = 'veh-409.png' },
  { id = 410, name = 'Manana', category = 'Saloons', file = 'veh-410.png' },
  { id = 411, name = 'Infernus', category = 'Sport Vehicles', file = 'veh-411.png' },
  { id = 412, name = 'Voodoo', category = 'Lowriders', file = 'veh-412.png' },
  { id = 413, name = 'Pony', category = 'Industrial', file = 'veh-413.png' },
  { id = 414, name = 'Mule', category = 'Industrial', file = 'veh-414.png' },
  { id = 415, name = 'Cheetah', category = 'Sport Vehicles', file = 'veh-415.png' },
  { id = 416, name = 'Ambulance', category = 'Public Service', file = 'veh-416.png' },
  { id = 417, name = 'Leviathan', category = 'Helicopters', file = 'veh-417.png' },
  { id = 418, name = 'Moonbeam', category = 'Station Wagons', file = 'veh-418.png' },
  { id = 419, name = 'Esperanto', category = 'Saloons', file = 'veh-419.png' },
  { id = 420, name = 'Taxi', category = 'Public Service', file = 'veh-420.png' },
  { id = 421, name = 'Washington', category = 'Saloons', file = 'veh-421.png' },
  { id = 422, name = 'Bobcat', category = 'Industrial', file = 'veh-422.png' },
  { id = 423, name = 'Mr Whoopee', category = 'Unique Vehicles', file = 'veh-423.png' },
  { id = 424, name = 'BF Injection', category = 'Off Road', file = 'veh-424.png' },
  { id = 425, name = 'Hunter', category = 'Helicopters', file = 'veh-425.png' },
  { id = 426, name = 'Premier', category = 'Saloons', file = 'veh-426.png' },
  { id = 427, name = 'Enforcer', category = 'Public Service', file = 'veh-427.png' },
  { id = 428, name = 'Securicar', category = 'Unique Vehicles', file = 'veh-428.png' },
  { id = 429, name = 'Banshee', category = 'Sport Vehicles', file = 'veh-429.png' },
  { id = 430, name = 'Predator', category = 'Boats', file = 'veh-430.png' },
  { id = 431, name = 'Bus', category = 'Public Service', file = 'veh-431.png' },
  { id = 432, name = 'Rhino', category = 'Public Service', file = 'veh-432.png' },
  { id = 433, name = 'Barracks', category = 'Public Service', file = 'veh-433.png' },
  { id = 434, name = 'Hotknife', category = 'Unique Vehicles', file = 'veh-434.png' },
  { id = 435, name = 'Article Trailer', category = 'Trailers', file = 'veh-435.png' },
  { id = 436, name = 'Previon', category = 'Saloons', file = 'veh-436.png' },
  { id = 437, name = 'Coach', category = 'Public Service', file = 'veh-437.png' },
  { id = 438, name = 'Cabbie', category = 'Public Service', file = 'veh-438.png' },
  { id = 439, name = 'Stallion', category = 'Convertibles', file = 'veh-439.png' },
  { id = 440, name = 'Rumpo', category = 'Industrial', file = 'veh-440.png' },
  { id = 441, name = 'RC Bandit', category = 'RC Vehicles', file = 'veh-441.png' },
  { id = 442, name = 'Romero', category = 'Unique Vehicles', file = 'veh-442.png' },
  { id = 443, name = 'Packer', category = 'Industrial', file = 'veh-443.png' },
  { id = 444, name = 'Monster', category = 'Off Road', file = 'veh-444.png' },
  { id = 445, name = 'Admiral', category = 'Saloons', file = 'veh-445.png' },
  { id = 446, name = 'Squallo', category = 'Boats', file = 'veh-446.png' },
  { id = 447, name = 'Seasparrow', category = 'Helicopters', file = 'veh-447.png' },
  { id = 448, name = 'Pizzaboy', category = 'Bikes', file = 'veh-448.png' },
  { id = 449, name = 'Tram', category = 'Unique Vehicles', file = 'veh-449.png' },
  { id = 450, name = 'Article Trailer 2', category = 'Trailers', file = 'veh-450.png' },
  { id = 451, name = 'Turismo', category = 'Sport Vehicles', file = 'veh-451.png' },
  { id = 452, name = 'Speeder', category = 'Boats', file = 'veh-452.png' },
  { id = 453, name = 'Reefer', category = 'Boats', file = 'veh-453.png' },
  { id = 454, name = 'Tropic', category = 'Boats', file = 'veh-454.png' },
  { id = 455, name = 'Flatbed', category = 'Industrial', file = 'veh-455.png' },
  { id = 456, name = 'Yankee', category = 'Industrial', file = 'veh-456.png' },
  { id = 457, name = 'Caddy', category = 'Unique Vehicles', file = 'veh-457.png' },
  { id = 458, name = 'Solair', category = 'Station Wagons', file = 'veh-458.png' },
  { id = 459, name = 'Topfun Van (Berkleys RC)', category = 'Industrial', file = 'veh-459.png' },
  { id = 460, name = 'Skimmer', category = 'Airplane', file = 'veh-460.png' },
  { id = 461, name = 'PCJ-600', category = 'Bikes', file = 'veh-461.png' },
  { id = 462, name = 'Faggio', category = 'Bikes', file = 'veh-462.png' },
  { id = 463, name = 'Freeway', category = 'Bikes', file = 'veh-463.png' },
  { id = 464, name = 'RC Baron', category = 'RC Vehicles', file = 'veh-464.png' },
  { id = 465, name = 'RC Raider', category = 'RC Vehicles', file = 'veh-465.png' },
  { id = 466, name = 'Glendale', category = 'Saloons', file = 'veh-466.png' },
  { id = 467, name = 'Oceanic', category = 'Saloons', file = 'veh-467.png' },
  { id = 468, name = 'Sanchez', category = 'Bikes', file = 'veh-468.png' },
  { id = 469, name = 'Sparrow', category = 'Helicopters', file = 'veh-469.png' },
  { id = 470, name = 'Patriot', category = 'Off Road', file = 'veh-470.png' },
  { id = 471, name = 'Quad', category = 'Bikes', file = 'veh-471.png' },
  { id = 472, name = 'Coastguard', category = 'Boats', file = 'veh-472.png' },
  { id = 473, name = 'Dinghy', category = 'Boats', file = 'veh-473.png' },
  { id = 474, name = 'Hermes', category = 'Saloons', file = 'veh-474.png' },
  { id = 475, name = 'Sabre', category = 'Sport Vehicles', file = 'veh-475.png' },
  { id = 476, name = 'Rustler', category = 'Airplane', file = 'veh-476.png' },
  { id = 477, name = 'ZR-350', category = 'Sport Vehicles', file = 'veh-477.png' },
  { id = 478, name = 'Walton', category = 'Industrial', file = 'veh-478.png' },
  { id = 479, name = 'Regina', category = 'Station Wagons', file = 'veh-479.png' },
  { id = 480, name = 'Comet', category = 'Convertibles', file = 'veh-480.png' },
  { id = 481, name = 'BMX', category = 'Bikes', file = 'veh-481.png' },
  { id = 482, name = 'Burrito', category = 'Industrial', file = 'veh-482.png' },
  { id = 483, name = 'Camper', category = 'Unique Vehicles', file = 'veh-483.png' },
  { id = 484, name = 'Marquis', category = 'Boats', file = 'veh-484.png' },
  { id = 485, name = 'Baggage', category = 'Unique Vehicles', file = 'veh-485.png' },
  { id = 486, name = 'Dozer', category = 'Unique Vehicles', file = 'veh-486.png' },
  { id = 487, name = 'Maverick', category = 'Helicopters', file = 'veh-487.png' },
  { id = 488, name = 'SAN News Maverick', category = 'Helicopters', file = 'veh-488.png' },
  { id = 489, name = 'Rancher', category = 'Off Road', file = 'veh-489.png' },
  { id = 490, name = 'FBI Rancher', category = 'Public Service', file = 'veh-490.png' },
  { id = 491, name = 'Virgo', category = 'Saloons', file = 'veh-491.png' },
  { id = 492, name = 'Greenwood', category = 'Saloons', file = 'veh-492.png' },
  { id = 493, name = 'Jetmax', category = 'Boats', file = 'veh-493.png' },
  { id = 494, name = 'Hotring Racer', category = 'Sport Vehicles', file = 'veh-494.png' },
  { id = 495, name = 'Sandking', category = 'Off Road', file = 'veh-495.png' },
  { id = 496, name = 'Blista Compact', category = 'Sport Vehicles', file = 'veh-496.png' },
  { id = 497, name = 'Police Maverick', category = 'Helicopters', file = 'veh-497.png' },
  { id = 498, name = 'Boxville', category = 'Industrial', file = 'veh-498.png' },
  { id = 499, name = 'Benson', category = 'Industrial', file = 'veh-499.png' },
  { id = 500, name = 'Mesa', category = 'Off Road', file = 'veh-500.png' },
  { id = 501, name = 'RC Goblin', category = 'RC Vehicles', file = 'veh-501.png' },
  { id = 502, name = 'Hotring Racer', category = 'Sport Vehicles', file = 'veh-502.png' },
  { id = 503, name = 'Hotring Racer', category = 'Sport Vehicles', file = 'veh-503.png' },
  { id = 504, name = 'Bloodring Banger', category = 'Saloons', file = 'veh-504.png' },
  { id = 505, name = 'Rancher', category = 'Off Road', file = 'veh-505.png' },
  { id = 506, name = 'Super GT', category = 'Sport Vehicles', file = 'veh-506.png' },
  { id = 507, name = 'Elegant', category = 'Saloons', file = 'veh-507.png' },
  { id = 508, name = 'Journey', category = 'Unique Vehicles', file = 'veh-508.png' },
  { id = 509, name = 'Bike', category = 'Bikes', file = 'veh-509.png' },
  { id = 510, name = 'Mountain Bike', category = 'Bikes', file = 'veh-510.png' },
  { id = 511, name = 'Beagle', category = 'Airplane', file = 'veh-511.png', lowQuality = true },
  { id = 512, name = 'Cropduster', category = 'Airplane', file = 'veh-512.png' },
  { id = 513, name = 'Stuntplane', category = 'Airplane', file = 'veh-513.png' },
  { id = 514, name = 'Tanker', category = 'Industrial', file = 'veh-514.png' },
  { id = 515, name = 'Roadtrain', category = 'Industrial', file = 'veh-515.png' },
  { id = 516, name = 'Nebula', category = 'Saloons', file = 'veh-516.png' },
  { id = 517, name = 'Majestic', category = 'Saloons', file = 'veh-517.png' },
  { id = 518, name = 'Buccaneer', category = 'Saloons', file = 'veh-518.png' },
  { id = 519, name = 'Shamal', category = 'Airplane', file = 'veh-519.png' },
  { id = 520, name = 'Hydra', category = 'Airplane', file = 'veh-520.png' },
  { id = 521, name = 'FCR-900', category = 'Bikes', file = 'veh-521.png' },
  { id = 522, name = 'NRG-500', category = 'Bikes', file = 'veh-522.png' },
  { id = 523, name = 'HPV1000', category = 'Public Service', file = 'veh-523.png' },
  { id = 524, name = 'Cement Truck', category = 'Industrial', file = 'veh-524.png' },
  { id = 525, name = 'Towtruck', category = 'Unique Vehicles', file = 'veh-525.png' },
  { id = 526, name = 'Fortune', category = 'Saloons', file = 'veh-526.png' },
  { id = 527, name = 'Cadrona', category = 'Saloons', file = 'veh-527.png' },
  { id = 528, name = 'FBI Truck', category = 'Public Service', file = 'veh-528.png' },
  { id = 529, name = 'Willard', category = 'Saloons', file = 'veh-529.png' },
  { id = 530, name = 'Forklift', category = 'Unique Vehicles', file = 'veh-530.png' },
  { id = 531, name = 'Tractor', category = 'Industrial', file = 'veh-531.png' },
  { id = 532, name = 'Combine Harvester', category = 'Unique Vehicles', file = 'veh-532.png' },
  { id = 533, name = 'Feltzer', category = 'Convertibles', file = 'veh-533.png' },
  { id = 534, name = 'Remington', category = 'Lowriders', file = 'veh-534.png' },
  { id = 535, name = 'Slamvan', category = 'Lowriders', file = 'veh-535.png' },
  { id = 536, name = 'Blade', category = 'Lowriders', file = 'veh-536.png' },
  { id = 537, name = 'Freight (Train)', category = 'Unique Vehicles', file = 'veh-537.png' },
  { id = 538, name = 'Brownstreak (Train)', category = 'Unique Vehicles', file = 'veh-538.png' },
  { id = 539, name = 'Vortex', category = 'Unique Vehicles', file = 'veh-539.png' },
  { id = 540, name = 'Vincent', category = 'Saloons', file = 'veh-540.png' },
  { id = 541, name = 'Bullet', category = 'Sport Vehicles', file = 'veh-541.png' },
  { id = 542, name = 'Clover', category = 'Saloons', file = 'veh-542.png' },
  { id = 543, name = 'Sadler', category = 'Industrial', file = 'veh-543.png' },
  { id = 544, name = 'Firetruck LA', category = 'Public Service', file = 'veh-544.png' },
  { id = 545, name = 'Hustler', category = 'Unique Vehicles', file = 'veh-545.png' },
  { id = 546, name = 'Intruder', category = 'Saloons', file = 'veh-546.png' },
  { id = 547, name = 'Primo', category = 'Saloons', file = 'veh-547.png' },
  { id = 548, name = 'Cargobob', category = 'Helicopters', file = 'veh-548.png' },
  { id = 549, name = 'Tampa', category = 'Saloons', file = 'veh-549.png' },
  { id = 550, name = 'Sunrise', category = 'Saloons', file = 'veh-550.png' },
  { id = 551, name = 'Merit', category = 'Saloons', file = 'veh-551.png' },
  { id = 552, name = 'Utility Van', category = 'Industrial', file = 'veh-552.png' },
  { id = 553, name = 'Nevada', category = 'Airplane', file = 'veh-553.png' },
  { id = 554, name = 'Yosemite', category = 'Industrial', file = 'veh-554.png' },
  { id = 555, name = 'Windsor', category = 'Convertibles', file = 'veh-555.png' },
  { id = 556, name = 'Monster "A"', category = 'Off Road', file = 'veh-556.png' },
  { id = 557, name = 'Monster "B"', category = 'Off Road', file = 'veh-557.png' },
  { id = 558, name = 'Uranus', category = 'Sport Vehicles', file = 'veh-558.png' },
  { id = 559, name = 'Jester', category = 'Sport Vehicles', file = 'veh-559.png' },
  { id = 560, name = 'Sultan', category = 'Saloons', file = 'veh-560.png' },
  { id = 561, name = 'Stratum', category = 'Station Wagons', file = 'veh-561.png' },
  { id = 562, name = 'Elegy', category = 'Saloons', file = 'veh-562.png' },
  { id = 563, name = 'Raindance', category = 'Helicopters', file = 'veh-563.png' },
  { id = 564, name = 'RC Tiger', category = 'RC Vehicles', file = 'veh-564.png' },
  { id = 565, name = 'Flash', category = 'Sport Vehicles', file = 'veh-565.png' },
  { id = 566, name = 'Tahoma', category = 'Lowriders', file = 'veh-566.png' },
  { id = 567, name = 'Savanna', category = 'Lowriders', file = 'veh-567.png' },
  { id = 568, name = 'Bandito', category = 'Off Road', file = 'veh-568.png' },
  { id = 569, name = 'Freight Flat Trailer (Train)', category = 'Trailers', file = 'veh-569.jpg', lowQuality = true },
  { id = 570, name = 'Streak Trailer (Train)', category = 'Trailers', file = 'veh-570.jpg', lowQuality = true },
  { id = 571, name = 'Kart', category = 'Unique Vehicles', file = 'veh-571.png' },
  { id = 572, name = 'Mower', category = 'Unique Vehicles', file = 'veh-572.png' },
  { id = 573, name = 'Dune', category = 'Off Road', file = 'veh-573.png' },
  { id = 574, name = 'Sweeper', category = 'Unique Vehicles', file = 'veh-574.png' },
  { id = 575, name = 'Broadway', category = 'Lowriders', file = 'veh-575.png' },
  { id = 576, name = 'Tornado', category = 'Lowriders', file = 'veh-576.png' },
  { id = 577, name = 'AT400', category = 'Airplane', file = 'veh-577.png' },
  { id = 578, name = 'DFT-30', category = 'Industrial', file = 'veh-578.png' },
  { id = 579, name = 'Huntley', category = 'Off Road', file = 'veh-579.png' },
  { id = 580, name = 'Stafford', category = 'Saloons', file = 'veh-580.png' },
  { id = 581, name = 'BF-400', category = 'Bikes', file = 'veh-581.png' },
  { id = 582, name = 'Newsvan', category = 'Industrial', file = 'veh-582.png' },
  { id = 583, name = 'Tug', category = 'Unique Vehicles', file = 'veh-583.png' },
  { id = 584, name = 'Petrol Trailer', category = 'Trailers', file = 'veh-584.png' },
  { id = 585, name = 'Emperor', category = 'Saloons', file = 'veh-585.png' },
  { id = 586, name = 'Wayfarer', category = 'Bikes', file = 'veh-586.png' },
  { id = 587, name = 'Euros', category = 'Sport Vehicles', file = 'veh-587.png' },
  { id = 588, name = 'Hotdog', category = 'Unique Vehicles', file = 'veh-588.png' },
  { id = 589, name = 'Club', category = 'Sport Vehicles', file = 'veh-589.png' },
  { id = 590, name = 'Freight Box Trailer (Train)', category = 'Trailers', file = 'veh-590.jpg', lowQuality = true },
  { id = 591, name = 'Article Trailer 3', category = 'Trailers', file = 'veh-591.png' },
  { id = 592, name = 'Andromada', category = 'Airplane', file = 'veh-592.png' },
  { id = 593, name = 'Dodo', category = 'Airplane', file = 'veh-593.png' },
  { id = 594, name = 'RC Cam', category = 'RC Vehicles', file = 'veh-594.png' },
  { id = 595, name = 'Launch', category = 'Boats', file = 'veh-595.png' },
  { id = 596, name = 'Police Car (LSPD)', category = 'Public Service', file = 'veh-596.png' },
  { id = 597, name = 'Police Car (SFPD)', category = 'Public Service', file = 'veh-597.png' },
  { id = 598, name = 'Police Car (LVPD)', category = 'Public Service', file = 'veh-598.png' },
  { id = 599, name = 'Police Ranger', category = 'Public Service', file = 'veh-599.png' },
  { id = 600, name = 'Picador', category = 'Industrial', file = 'veh-600.png' },
  { id = 601, name = 'S.W.A.T.', category = 'Public Service', file = 'veh-601.png' },
  { id = 602, name = 'Alpha', category = 'Sport Vehicles', file = 'veh-602.png' },
  { id = 603, name = 'Phoenix', category = 'Sport Vehicles', file = 'veh-603.png' },
  { id = 604, name = 'Glendale Shit', category = 'Saloons', file = 'veh-604.png' },
  { id = 605, name = 'Sadler Shit', category = 'Industrial', file = 'veh-605.png' },
  { id = 606, name = 'Baggage Trailer "A"', category = 'Trailers', file = 'veh-606.png' },
  { id = 607, name = 'Baggage Trailer "B"', category = 'Trailers', file = 'veh-607.png' },
  { id = 608, name = 'Tug Stairs Trailer', category = 'Trailers', file = 'veh-608.png' },
  { id = 609, name = 'Boxville', category = 'Industrial', file = 'veh-609.png' },
  { id = 610, name = 'Farm Trailer', category = 'Trailers', file = 'veh-610.png' },
}
