--[[ Модуль: публикация locals в env для 2-го core-chunk и late modules (checker). ]]
if rawget(_G, '__REPORT_DESK_BUNDLE_ACTIVE') ~= true then return end

-- Без local e: у core_a уже ~200 locals (ещё один local ломает loadstring).
if type(getfenv(1)) ~= 'table' then return end
if type(outbound) ~= 'table' then
    error('[Report Desk] outbound not initialized before env export')
end
if type(chatSeen) ~= 'table' then
    error('[Report Desk] chatSeen not initialized before env export')
end

getfenv(1).imgui = imgui
getfenv(1).sampev = sampev
getfenv(1).vkeys = vkeys
getfenv(1).new = new
getfenv(1).sizeof = sizeof
getfenv(1).u8 = u8
getfenv(1).ffi = ffi
getfenv(1).memory = memory
getfenv(1).cheat_user32 = cheat_user32
getfenv(1).deskVeh = deskVeh
getfenv(1).deskGrid = deskGrid
getfenv(1).deskTex = deskTex
getfenv(1).deskTexPipeline = deskTexPipeline
getfenv(1).deskTexLoad = deskTexLoad
getfenv(1).deskSpectateStats = deskSpectateStats
getfenv(1).deskIngest = deskIngest
getfenv(1).settings = settings
getfenv(1).deskCache = deskCache
getfenv(1).deskInputState = deskInputState
getfenv(1).showWindow = showWindow
getfenv(1).threads = threads
getfenv(1).threadOrder = threadOrder
getfenv(1).threadCount = threadCount
getfenv(1).MAX_PLAYER_ID = MAX_PLAYER_ID
getfenv(1).findPlayerIdByNick = findPlayerIdByNick
getfenv(1).refreshPlayerNickCache = refreshPlayerNickCache
getfenv(1).nickKey = nickKey
getfenv(1).chatSeen = chatSeen
getfenv(1).outbound = outbound
_G.chatSeen = chatSeen
_G.outbound = outbound
getfenv(1).trim = trim
getfenv(1).stripTags = stripTags
getfenv(1).stripChatTimestamp = stripChatTimestamp
getfenv(1).chatLineSeenKey = chatLineSeenKey
getfenv(1).markChatLineSeen = markChatLineSeen
getfenv(1).markDirtyThreads = markDirtyThreads
getfenv(1).clearPendingOutbound = clearPendingOutbound
getfenv(1).tryIngestAdminReplyLine = tryIngestAdminReplyLine
getfenv(1).processChatLineIngest = processChatLineIngest
getfenv(1).profanityIsLineSeen = profanityIsLineSeen
getfenv(1).checkProfanityFromChatLine = checkProfanityFromChatLine
getfenv(1).checkProfanityOutgoing = checkProfanityOutgoing
getfenv(1).installProfanityHooks = installProfanityHooks
getfenv(1).tryInterceptSplitAnsCommand = tryInterceptSplitAnsCommand
getfenv(1).handleOutgoingAnsCommand = handleOutgoingAnsCommand
getfenv(1).deskLeaveSpectateMode = deskLeaveSpectateMode
getfenv(1).deskApplyInputPolicy = deskApplyInputPolicy
getfenv(1).markDirtySettings = markDirtySettings
getfenv(1).say = say
getfenv(1).sendChat = sendChat
getfenv(1).getLocalAdminLevel = getLocalAdminLevel
getfenv(1).profanity_words = profanity_words
getfenv(1).quickScenarios = quickScenarios
getfenv(1).activeTab = activeTab
getfenv(1).filterMode = filterMode
getfenv(1).searchBuf = searchBuf
getfenv(1).replyBuf = replyBuf
getfenv(1).cmdBuf = cmdBuf
getfenv(1).selectedKey = selectedKey
getfenv(1).pendingAuto = pendingAuto
getfenv(1).ruleCooldowns = ruleCooldowns
getfenv(1).replyUi = replyUi
getfenv(1).catWarmup = catWarmup
getfenv(1).cheatState = cheatState
getfenv(1).uiCheatGm = uiCheatGm
getfenv(1).uiCheatWh = uiCheatWh
getfenv(1).uiCheatAb = uiCheatAb
getfenv(1).uiCheatGmStart = uiCheatGmStart
getfenv(1).uiCheatWhStart = uiCheatWhStart
getfenv(1).uiCheatHud = uiCheatHud
getfenv(1).uiCheatMaskId = uiCheatMaskId
getfenv(1).uiCheatAbSpeed = uiCheatAbSpeed
getfenv(1).cheatsUiSynced = cheatsUiSynced
getfenv(1).cheatsStartupDone = cheatsStartupDone
getfenv(1).skinCatalog = skinCatalog
getfenv(1).skinCatalogById = skinCatalogById
getfenv(1).skinUiTabActive = skinUiTabActive
getfenv(1).skinTabEntered = skinTabEntered
getfenv(1).skinSelectedId = skinSelectedId
getfenv(1).skinNearbyCache = skinNearbyCache
getfenv(1).skinLoadFailLogged = skinLoadFailLogged
getfenv(1).skinTargetBuf = skinTargetBuf
getfenv(1).skinFilterBuf = skinFilterBuf
getfenv(1).skinFiltered = skinFiltered
getfenv(1).skinsTabSynced = skinsTabSynced
getfenv(1).uiSkinRadius = uiSkinRadius
getfenv(1).uiAdminLevel = uiAdminLevel
getfenv(1).skinRadiusJob = skinRadiusJob
getfenv(1).skinApplyCooldownUntil = skinApplyCooldownUntil
getfenv(1).rulesEditorDirty = rulesEditorDirty
getfenv(1).dirtySettings = dirtySettings
getfenv(1).dirtyThreads = dirtyThreads
getfenv(1).RECENT = RECENT
getfenv(1).lastMapPrune = lastMapPrune
getfenv(1).lastSettingsSave = lastSettingsSave
getfenv(1).lastThreadsSave = lastThreadsSave
getfenv(1).scenariosGen = scenariosGen
getfenv(1).uiSound = uiSound
getfenv(1).deskReplyBuf = deskReplyBuf
getfenv(1).editCqLabel = editCqLabel
getfenv(1).editCqText = editCqText
getfenv(1).uiAutoRulesEnabled = uiAutoRulesEnabled
getfenv(1).uiAutoTimeEnabled = uiAutoTimeEnabled
getfenv(1).uiAutoGgEnabled = uiAutoGgEnabled
getfenv(1).uiWatchAutoNotify = uiWatchAutoNotify
getfenv(1).uiSpecHud = uiSpecHud
getfenv(1).uiSpecAutoSt = uiSpecAutoSt
getfenv(1).uiSpecAutoRefresh = uiSpecAutoRefresh
getfenv(1).uiSpecHudPersist = uiSpecHudPersist
getfenv(1).uiSpecSpMenuSound = uiSpecSpMenuSound
getfenv(1).uiSpecVehicleHud = uiSpecVehicleHud
getfenv(1).uiSpecKeysHud = uiSpecKeysHud
getfenv(1).uiSpecWheelZoom = uiSpecWheelZoom
getfenv(1).uiProfanityFilter = uiProfanityFilter
getfenv(1).uiRemoteChatSamp = uiRemoteChatSamp
getfenv(1).uiProfanitySound = uiProfanitySound
getfenv(1).uiAdminPunishEnabled = uiAdminPunishEnabled
getfenv(1).uiAdminPunishSendAns = uiAdminPunishSendAns
getfenv(1).uiAdminPunishSignCmd = uiAdminPunishSignCmd
getfenv(1).ruleKwBulk = ruleKwBulk
getfenv(1).ruleTestBuf = ruleTestBuf
getfenv(1).ruleTestResult = ruleTestResult
getfenv(1).myPlayerNick = myPlayerNick
getfenv(1).myNickTick = myNickTick
getfenv(1).playerNickToId = playerNickToId
getfenv(1).playerNickCacheAt = playerNickCacheAt
getfenv(1).chatLogReady = chatLogReady
getfenv(1).styleApplied = styleApplied
getfenv(1).sessionLive = sessionLive
getfenv(1).deskConfigReady = deskConfigReady
getfenv(1).totalUnread = totalUnread
getfenv(1).editRuleName = editRuleName
getfenv(1).editRulePayload = editRulePayload
getfenv(1).ruleKwNew = ruleKwNew
if deskSpectatingNow then _G.deskSpectatingNow = deskSpectatingNow end
if deskSetPlayerSpectating then _G.deskSetPlayerSpectating = deskSetPlayerSpectating end
if deskReinstallSpMenuHooks then _G.deskReinstallSpMenuHooks = deskReinstallSpMenuHooks end
if deskEnsureAllHooks then _G.deskEnsureAllHooks = deskEnsureAllHooks end
if deskHoldSampChatInput then _G.deskHoldSampChatInput = deskHoldSampChatInput end
if deskReleaseSampChatInput then _G.deskReleaseSampChatInput = deskReleaseSampChatInput end
if deskCloseSampChatIfOpen then _G.deskCloseSampChatIfOpen = deskCloseSampChatIfOpen end
if deskRestoreSampChatIfNeeded then _G.deskRestoreSampChatIfNeeded = deskRestoreSampChatIfNeeded end
if deskShouldBlockGameInput then _G.deskShouldBlockGameInput = deskShouldBlockGameInput end
if deskSpectateCameraBlocked then _G.deskSpectateCameraBlocked = deskSpectateCameraBlocked end
if deskRestoreSpectateCamera then _G.deskRestoreSpectateCamera = deskRestoreSpectateCamera end
if deskMimguiHideCursor then _G.deskMimguiHideCursor = deskMimguiHideCursor end
if deskSpectateCameraOwnsInput then _G.deskSpectateCameraOwnsInput = deskSpectateCameraOwnsInput end
if deskSpectateOverlayInputAllowed then _G.deskSpectateOverlayInputAllowed = deskSpectateOverlayInputAllowed end
if deskEnableUiCursorForSamp then _G.deskEnableUiCursorForSamp = deskEnableUiCursorForSamp end
if deskCache then _G.deskCache = deskCache end
getfenv(1).SKIN_RADIUS_MIN = SKIN_RADIUS_MIN
getfenv(1).SKIN_RADIUS_MAX = SKIN_RADIUS_MAX
getfenv(1).SKIN_RADIUS_MAX_TARGETS = SKIN_RADIUS_MAX_TARGETS
getfenv(1).SKIN_LIST_MAX_TARGETS = SKIN_LIST_MAX_TARGETS
getfenv(1).SKIN_APPLY_COOLDOWN_SEC = SKIN_APPLY_COOLDOWN_SEC
getfenv(1).MOUSE_BIND_VKS = MOUSE_BIND_VKS
getfenv(1).AUTO_RETRY_MS = AUTO_RETRY_MS
getfenv(1).AUTO_RETRY_MAX = AUTO_RETRY_MAX
getfenv(1).AUTO_REPLY_DELAY_MS = AUTO_REPLY_DELAY_MS
getfenv(1).PLAYER_NICK_CACHE_INTERVAL = PLAYER_NICK_CACHE_INTERVAL
getfenv(1).CHAT_UI_RENDER_MAX = CHAT_UI_RENDER_MAX
getfenv(1).DEFAULT_QUICK_SCENARIOS = DEFAULT_QUICK_SCENARIOS
