-- Admin Report Desk user settings (UTF-8)
-- report-desk-user-config: utf-8
-- Scenarios. Auto-reply keywords are built-in; edit toggles/text in Report Desk settings.
return {
  strings = {
    gg_reply = "Хорошей игры на ARP Blue)",
    tech_reply = "Лучше обратитесь в технический раздел на форуме ARP",
    watch_notify = "see",
  },
  composer_quick_buttons = {
    {
      id = "gg",
      label = "GG",
      text = "Хорошей игры на ARP Blue)",
    },
    {
      id = "tech",
      label = "Техничка",
      text = "Лучше обратитесь в технический раздел на форуме ARP",
    },
  },
  quick_scenarios = {
    {
      label = "GPS Тир",
      enabled = true,
      match = "contains",
      priority = 40,
      skip_if_report_id = true,
      action = "reply",
      reply = "Тир для прокачка скиллов по /gps 7 2",
      keywords = {"где+тир", "как+качать+скилл", "тир+gps", "скилл+тир", "прокачать+скилл", "качать+скилл", "стрелковый+тир", "спец+тир"},
    },
    {
      label = "GPS Транспортная",
      enabled = true,
      match = "contains",
      priority = 35,
      skip_if_report_id = true,
      action = "reply",
      reply = "Транспортная компания по /gps 9",
      keywords = {"транспортная+компания", "дальнобойщик", "работ+дальноб", "найти+работу+дальноб", "где+дальноб", "gps+транспорт", "дальнобой+gps", "работа+дальнобой", "устроиться+транспорт", "транспорт+компан+устро", "компан+устроиться"},
    },
    {
      label = "GPS Военкомат ЛВ",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "Военкомат в Лас-Вентурас: /gps 1 7",
      keywords = {"военкомат", "воинкомат", "военком", "военкомат+лв", "военкомат+гпс"},
    },
    {
      label = "Найти отель",
      enabled = true,
      match = "contains",
      priority = 50,
      skip_if_report_id = true,
      action = "reply",
      reply = "Список отелей и цены: /price",
      keywords = {"где+отель", "как+найти+отель", "отель+gps", "найти+отель", "гостиница+где", "куда+заселиться"},
    },
    {
      label = "Слёт номера отеля",
      enabled = false,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "Список отелей и цены: /price",
      keywords = {"слетают+номер", "слетают+отел", "во+сколько+отел", "слетают+номера", "слет+отел"},
    },
    {
      label = "Слить авто в гос",
      enabled = true,
      match = "contains",
      priority = 35,
      skip_if_report_id = true,
      action = "reply",
      reply = "Продать в гос: /home — на ресепшене",
      keywords = {"слить+авто", "слить+машину", "слить+тачку", "слить+машин", "сдать+авто", "продать+гос", "сдать+в+гос", "слить+в+гос", "продать+машину+гос", "слить+гос", "продать+государ", "государству+продать"},
    },
    {
      label = "Найти свою машину",
      enabled = true,
      match = "contains",
      priority = 40,
      skip_if_report_id = true,
      action = "reply",
      reply = "Найти авто: /home",
      keywords = {"где+моя+машина", "найти+машину", "где+мой+авто", "найти+свою", "купил+машину+где", "машина+где", "купил+машину+нет", "машины+нет", "машину+нет", "заспавнить+авто", "заспавнить+машин", "спавн+машин", "заспанить+авто", "заспавнить+машину", "пропала+машин", "машина+пропала", "потерял+машин", "пропал+авто"},
    },
    {
      label = "Выселиться из отеля",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "Выселиться: ресепшен отеля на 1 этаже",
      keywords = {"выселиться", "выселится", "как+выйти+из+отеля", "покинуть+отель"},
    },
    {
      label = "Автобусник / Таксист",
      enabled = true,
      match = "contains",
      priority = 45,
      skip_if_report_id = true,
      action = "reply",
      reply = "Устроиться: 2 этаж мэрии, /gps 1",
      keywords = {"водитель+автобуса", "автобусник", "автобусником", "работ+автобус", "устроиться+автобус", "работа+автобус", "где+автобусником", "водитель+автобус", "таксист+устроиться", "не+водитель+автобус", "начать+автобус", "работать+автобус", "центр+занятости", "где+работа+устроиться"},
    },
    {
      label = "Анонсы /news",
      enabled = true,
      match = "contains",
      priority = 40,
      skip_if_report_id = true,
      action = "reply",
      reply = "Анонсы собеседований: /news",
      keywords = {"собеседование", "собеседован", "собес", "список+собес", "список+собеседован", "посмотреть+собес", "посмотреть+список+собес", "как+посмотреть+собес", "как+собес", "когда+собес", "анонс+набор", "анонс+собес", "когда+набор", "/news"},
    },
    {
      label = "Набор /join",
      enabled = true,
      match = "contains",
      priority = 38,
      skip_if_report_id = true,
      action = "reply",
      reply = "Набор в организацию: /join",
      keywords = {"набор+в+орг", "набор+орга", "как+узнать+набор", "где+набор"},
    },
    {
      label = "Запустить двигатель",
      enabled = true,
      match = "contains",
      priority = 45,
      skip_if_report_id = true,
      action = "reply",
      reply = "Запустить/заглушить двигатель: /e",
      keywords = {"запустить+двигатель", "завести+мотор", "команда+двигатель", "двигатель+команда", "как+завести", "запуск+мотора", "завести+двигатель"},
    },
    {
      label = "Багажник",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "Открыть/закрыть багажник: /b",
      keywords = {"багажник", "как+открыть+багажник", "открыть+бак", "задний+бак"},
    },
    {
      label = "Продать оружие",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "Передать оружие: /sellgun [id]",
      keywords = {"передать+оружие", "продать+оружие", "sellgun", "как+передать+оружие"},
    },
    {
      label = "Купить оружие",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "Оружейный магазин: /price",
      keywords = {"где+купить+оружие", "купить+оружие", "оружейный+магазин", "оружие+где"},
    },
    {
      label = "Лицензия — где",
      enabled = true,
      match = "contains",
      priority = 32,
      skip_if_report_id = true,
      action = "reply",
      reply = "Лицензеры в мэрии: /gps 1",
      keywords = {"лицензия+оружие", "лиц+на+оружие", "как+получить+лицензию", "лицензия+где", "лиц+оружие", "лиц+ган", "лиценз+ган", "ганы+лиценз", "получить+ган"},
    },
    {
      label = "Список лицензеров",
      enabled = true,
      match = "contains",
      priority = 28,
      skip_if_report_id = true,
      action = "reply",
      reply = "Список лицензеров: /liclist",
      keywords = {"liclist", "список+лицензер", "кто+лицензер"},
    },
    {
      label = "Скиллы /skill",
      enabled = true,
      match = "contains",
      priority = 35,
      skip_if_report_id = true,
      action = "reply",
      reply = "Посмотреть навыки: /skill",
      keywords = {"посмотреть+скиллы", "как+смотреть+скилл", "свои+навыки", "где+скилл", "/skill", "скилы", "скиллы"},
    },
    {
      label = "Анимация /reset",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "нажать на enter попробуйте",
      keywords = {"убрать+анимку", "отключить+анимацию", "анимация+убрать", "застрял+аним", "анимка", "/anim", "застрял+в+аним"},
    },
    {
      label = "Инвентарь /i",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "Открыть инвентарь: /i",
      keywords = {"инвентарь", "как+инвентарь", "как+открыть+инвентарь", "открыть+инвентарь", "где+инвентарь", "нет+инвентаря"},
    },
    {
      label = "Чат фракции /f",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "РП чат фракции: /f",
      keywords = {"чат+фракции", "чат+орги", "как+писать+в+фракцию"},
    },
    {
      label = "Нон-РП чат /fn",
      enabled = true,
      match = "contains",
      priority = 29,
      skip_if_report_id = true,
      action = "reply",
      reply = "Нон-РП чат фракции: /fn",
      keywords = {"нрп+чат", "нон+рп+чат"},
    },
    {
      label = "Чат банды /rn",
      enabled = true,
      match = "contains",
      priority = 28,
      skip_if_report_id = true,
      action = "reply",
      reply = "Чат банды: /rn",
      keywords = {"чат+банды"},
    },
    {
      label = "Семейный чат /fm",
      enabled = true,
      match = "contains",
      priority = 27,
      skip_if_report_id = true,
      action = "reply",
      reply = "Семейный чат: /fm",
      keywords = {"семейный+чат", "чат+семь", "семья+чат"},
    },
    {
      label = "Список замов /zamlist",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "Список заместителей: /zamlist",
      keywords = {"список+замов", "zamlist", "замы+фракции", "кто+замы", "зам+список"},
    },
    {
      label = "Онлайн фракции /find",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "Участники онлайн: /find",
      keywords = {"кто+в+сети+орги", "участники+онлайн", "онлайн+фракции", "члены+онлайн", "кто+в+сети+фракции"},
    },
    {
      label = "Полный список /showall",
      enabled = true,
      match = "contains",
      priority = 24,
      skip_if_report_id = true,
      action = "reply",
      reply = "Полный список фракции: /showall",
      keywords = {"полный+список", "showall", "все+участники", "список+фракции"},
    },
    {
      label = "Звёзды розыска",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "Снять звёзды: сдайтесь в полицейском участке",
      keywords = {"снять+звезды", "убрать+звезды", "звезды+розыска", "как+снять+розыск", "розыск+как+снять", "сбросить+розыск", "розыск+снять", "как+розыск+снять"},
    },
    {
      label = "Бензин/АЗС",
      enabled = true,
      match = "contains",
      priority = 35,
      skip_if_report_id = true,
      action = "reply",
      reply = "Купите канистру на ближайшей АЗС",
      keywords = {"нет+бензина", "кончился+бензин", "нет+топлива", "бензин+кончился", "азс+где", "канистр", "купить+канистр", "где+азс", "купить+бензин", "купить+топлив", "не+могу+купить+топлив"},
    },
    {
      label = "Механик /c 090",
      enabled = true,
      match = "contains",
      priority = 36,
      skip_if_report_id = true,
      action = "reply",
      reply = "Вызвать механика: /c 090",
      keywords = {"вызвать+механика", "механик+номер", "/c 090", "как+вызвать+механика", "эвакуатор", "010", "полом+машин"},
    },
    {
      label = "Батл Пасс /bp",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "Battle Pass: /bp",
      keywords = {"батл+пасс", "battle+pass", "бп+команда", "как+смотреть+бп", "баттл+пасс", "battle+pass+где", "забрать+наград", "награды+бп", "награды+bp", "где+награды+бп"},
    },
    {
      label = "Прогресс БП /tasks",
      enabled = true,
      match = "contains",
      priority = 24,
      skip_if_report_id = true,
      action = "reply",
      reply = "Прогресс заданий: /tasks",
      keywords = {"прогресс+бп", "задания+бп", "tasks", "задания+bp"},
    },
    {
      label = "Advance Credits вЂ” help",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "Advance Credits: /creditshelp",
      keywords = {"адванс+кредиты", "advance+credits", "creditshelp", "кредиты+как+использовать", "адванс+кредит", "меню+кредит", "адванс+credits"},
    },
    {
      label = "Баланс кредитов /st",
      enabled = true,
      match = "contains",
      priority = 19,
      skip_if_report_id = true,
      action = "reply",
      reply = "Баланс кредитов: /st",
      keywords = {"баланс+кредит", "сколько+кредит", "кредит+баланс"},
    },
    {
      label = "Спавн точка /setspawn",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "Сменить место спавна: /setspawn",
      keywords = {"место+спавна", "setspawn", "сменить+спавн", "поменять+спавн", "спавн+орга", "изменить+спавн", "точка+спавна"},
    },
    {
      label = "Подать объявление /ad",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "Подать объявление: /ad [текст]",
      keywords = {"как+подать+объявление", "подать+объявление", "/ad", "объявление+команда", "объявление"},
    },
    {
      label = "Позвонить /c",
      enabled = true,
      match = "contains",
      priority = 22,
      skip_if_report_id = true,
      action = "reply",
      reply = "Позвонить: /c [номер]",
      keywords = {"как+позвонить", "позвонить+игроку", "как+звонить", "говорить+телефон", "номер+телефон"},
    },
    {
      label = "Купить телефон",
      enabled = true,
      match = "contains",
      priority = 21,
      skip_if_report_id = true,
      action = "reply",
      reply = "Телефон — в магазине 24/7",
      keywords = {"купить+телефон", "телефон+где", "где+телефон", "нет+телефона"},
    },
    {
      label = "Микрофон (войс)",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "Микрофон: F2",
      keywords = {"включить+микрофон", "войс+чат", "микрофон+как", "f2+микро", "voice+chat", "не+работает+микро", "войсом+пользов"},
    },
    {
      label = "Варн инфо /warninfo",
      enabled = true,
      match = "contains",
      priority = 15,
      skip_if_report_id = true,
      action = "reply",
      reply = "Информация о предупреждениях: /warninfo",
      keywords = {"сколько+варнов", "мои+варны", "warninfo", "варн+инфо", "срок+варна"},
    },
    {
      label = "Лицензии /lic",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "Показать свои лицензии: /lic",
      keywords = {"показать+лицензии", "мои+лицензии", "/lic", "лицензии+команда", "как+показать+лиц"},
    },
    {
      label = "Квест трамвай",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "Квест с трамваем: НПС у депо /gps 5, проедьте 1 круг",
      keywords = {"квест+трамвай", "трамвай+квест", "квест+трамвае", "как+сделать+трамвай", "трамвайный+квест"},
    },
    {
      label = "Загрузить металл /buym",
      enabled = true,
      match = "contains",
      priority = 26,
      skip_if_report_id = true,
      action = "reply",
      reply = "Загрузить металл: /buym на чекпоинте шахты",
      keywords = {"загрузить+металл", "металл+в+грузовик", "как+загрузить+руду", "buym", "металл+куда"},
    },
    {
      label = "GPS Шахта",
      enabled = true,
      match = "contains",
      priority = 24,
      skip_if_report_id = true,
      action = "reply",
      reply = "Шахта: /gps 5",
      keywords = {"шахта+квест", "где+шахта", "шахта+где", "шахта+gps"},
    },
    {
      label = "Покинуть фракцию /leave",
      enabled = true,
      match = "contains",
      priority = 15,
      skip_if_report_id = true,
      action = "reply",
      reply = "Покинуть организацию: /leave",
      keywords = {"выйти+из+орги", "уйти+из+фракции", "выйти+организа", "/leave", "как+уйти+из+банды", "выйти+гос"},
    },
    {
      label = "Донат /donate",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "Донат: /donate",
      keywords = {"донат+команда", "пополнить+донат", "донат+баланс", "где+донат", "/donate", "как+задонатить"},
    },
    {
      label = "Полноэкранный режим",
      enabled = true,
      match = "contains",
      priority = 10,
      skip_if_report_id = true,
      action = "reply",
      reply = "Alt + Enter",
      keywords = {"полноэкранный", "полный+экран", "оконный+режим", "alt+enter", "как+сделать+полный+экран"},
    },
  },
}
