-- Admin Report Desk user settings (UTF-8)
-- report-desk-user-config: utf-8
-- Scenarios. Auto-reply keywords are built-in; edit toggles/text in Report Desk settings.
return {
  strings = {
    gg_reply = "Хорошей игры на ARP Blue)",
    tech_reply = "Лучше обратитесь в технический раздел на форуме ARP",
    watch_notify = "see",
  },
  composer_quick_buttons = {
    {
      id = "gg",
      label = "GG",
      text = "Хорошей игры на ARP Blue)",
    },
    {
      id = "tech",
      label = "Техничка",
      text = "Лучше обратитесь в технический раздел на форуме ARP",
    },
  },
  quick_scenarios = {
    {
      label = "GPS Тир",
      enabled = true,
      match = "contains",
      priority = 40,
      skip_if_report_id = true,
      action = "reply",
      reply = "Тир: /gps 7-2",
      keywords = {"где+тир", "тир+gps", "gps+тир", "стрелковый+тир", "спец+тир", "как+попасть+тир", "найти+тир", "тир+где", "тир+сан"},
      negative_keywords = {"скилл", "skill", "чекнуть", "посмотреть+навык", "продвинут", "владения+оруж", "навыки+оруж"},
    },
    {
      label = "GPS Транспортная",
      enabled = true,
      match = "contains",
      priority = 35,
      skip_if_report_id = true,
      action = "reply",
      reply = "/gps 9",
      keywords = {"транспортная+компания", "дальнобойщик", "работ+дальноб", "найти+работу+дальноб", "где+дальноб", "gps+транспорт", "дальнобой+gps", "работа+дальнобой", "устроиться+транспорт", "что+гпс+9", "гпс+9", "дальнобоем+работать"},
    },
    {
      label = "GPS Военкомат ЛВ",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "Военкомат в Лас-Вентурас: /gps 1 7",
      keywords = {"военкомат", "воинкомат", "военком", "военкомат+лв", "военкомат+гпс"},
    },
    {
      label = "Найти отель",
      enabled = true,
      match = "contains",
      priority = 50,
      skip_if_report_id = true,
      action = "reply",
      reply = "Список отелей и цены: /price",
      keywords = {"где+отель", "как+найти+отель", "отель+gps", "найти+отель", "гостиница+где", "куда+заселиться", "как+посмотреть+отель"},
      negative_keywords = {"собес"},
    },
    {
      label = "Слёт номера отеля",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "Номера отелей слетают около 00:03",
      keywords = {"слетают+номер", "слетают+отел", "во+сколько+отел", "слетают+номера", "слет+отел", "сколько+слетают+отел"},
      negative_keywords = {"найти+отель", "где+отель", "купить+отель"},
    },
    {
      label = "Слить авто в гос",
      enabled = true,
      match = "contains",
      priority = 35,
      skip_if_report_id = true,
      action = "reply",
      reply = "Продать в гос: ресепшен отеля (/home /hotel)",
      keywords = {"слить+авто+гос", "слить+машину+гос", "слить+тачку+гос", "продать+авто+гос", "продать+машину+гос", "сдать+авто+гос", "сдать+в+гос", "слить+в+гос", "тачку+в+гос", "машину+вгос", "продать+гос"},
    },
    {
      label = "Найти свою машину",
      enabled = true,
      match = "contains",
      priority = 42,
      skip_if_report_id = true,
      action = "reply",
      reply = "Заспавнить авто: /home /hotel (синяя метка у отеля)",
      keywords = {"где+моя+машина", "найти+машину", "где+мой+авто", "купил+машину+где", "машина+где", "заспавнить+авто", "заспавнить+машин", "спавн+машин", "заспавнить+машину", "пропала+машин", "машина+пропала", "как+найти+машину", "купленную+машину", "заспавнить+свой+авто", "не+заспавнил", "свой+тс+вызвать"},
      negative_keywords = {"ключ", "аренд", "скутер", "unrent", "крыш"},
    },
    {
      label = "Выселиться из отеля",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "Выселиться: в меню отеля на ресепшене",
      keywords = {"выселиться", "выселится", "как+выйти+из+отеля", "покинуть+отель", "выселится+отеля", "выселится+жилья"},
    },
    {
      label = "Работа в мэрии",
      enabled = true,
      match = "contains",
      priority = 44,
      skip_if_report_id = true,
      action = "reply",
      reply = "Работа в мэрии (граждане): /gps 1 2, 2 этаж",
      keywords = {"работа+мэри", "устроиться+мэри", "работу+мэри", "устроиться+на+работу+мэри", "граждан+мэри", "работа+мерии", "устроиться+мерии"},
      negative_keywords = {"автобус", "таксист", "заблуд", "памагити"},
    },
    {
      label = "Автобусник",
      enabled = true,
      match = "contains",
      priority = 45,
      skip_if_report_id = true,
      action = "reply",
      reply = "Устроиться автобусником: 2 этаж мэрии, /gps 1",
      keywords = {"водитель+автобуса", "автобусник", "автобусником", "работ+автобус", "устроиться+автобус", "работа+автобус", "где+автобусником", "водитель+автобус", "не+водитель+автобус", "начать+автобус", "работать+автобус", "центр+занятости"},
    },
    {
      label = "Устроиться таксистом",
      enabled = true,
      match = "contains",
      priority = 44,
      skip_if_report_id = true,
      action = "reply",
      reply = "Устроиться таксистом: 2 этаж мэрии, /gps 1",
      keywords = {"таксист+устроиться", "устроиться+таксист", "работа+таксист", "работать+таксист", "где+работа+устроиться", "устроиться+таксистом", "работа+таксистом"},
      negative_keywords = {"вызвать+такси", "позвать+такси", "позвонить+такси", "заказать+такси", "как+позвонить", "вызов+такси", "/c 555"},
    },
    {
      label = "Вызвать такси",
      enabled = true,
      match = "contains",
      priority = 48,
      skip_if_report_id = true,
      action = "reply",
      reply = "Вызвать такси: /c 555",
      keywords = {"вызвать+такси", "позвать+такси", "позвонить+такси", "как+вызвать+такси", "как+позвонить+такси", "такси+вызов", "заказать+такси", "номер+такси", "/c 555"},
    },
    {
      label = "Анонсы /news",
      enabled = true,
      match = "contains",
      priority = 40,
      skip_if_report_id = true,
      action = "reply",
      reply = "Собеседования: /join, анонсы: /news",
      keywords = {"собеседование", "собеседован", "собес", "список+собес", "список+собеседован", "посмотреть+собес", "посмотреть+список+собес", "как+посмотреть+собес", "как+собес", "когда+собес", "анонс+набор", "анонс+собес", "когда+набор", "/news", "куда+собес"},
    },
    {
      label = "Набор /join",
      enabled = true,
      match = "contains",
      priority = 38,
      skip_if_report_id = true,
      action = "reply",
      reply = "Набор в организацию: /join",
      keywords = {"набор+в+орг", "набор+орга", "как+узнать+набор", "где+набор"},
      negative_keywords = {"собес"},
    },
    {
      label = "Запустить двигатель",
      enabled = true,
      match = "contains",
      priority = 45,
      skip_if_report_id = true,
      action = "reply",
      reply = "Запустить/заглушить двигатель: /e или Ctrl",
      keywords = {"запустить+двигатель", "завести+мотор", "команда+двигатель", "двигатель+команда", "как+завести", "запуск+мотора", "завести+двигатель", "транспорт+завести", "завести+транспорт"},
    },
    {
      label = "Багажник",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "Открыть/закрыть багажник: /b",
      keywords = {"багажник", "как+открыть+багажник", "открыть+бак", "задний+бак"},
    },
    {
      label = "Ключи от авто /allow",
      enabled = true,
      match = "contains",
      priority = 41,
      skip_if_report_id = true,
      action = "reply",
      reply = "Передать ключи от машины: /allow [id]",
      keywords = {"передать+ключ", "ключ+машин", "ключи+машин", "ключ+авто", "дать+ключ"},
    },
    {
      label = "Продать оружие",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "Передать оружие: /sellgun [id] (только банды)",
      keywords = {"передать+оружие", "продать+оружие", "sellgun", "как+передать+оружие"},
      negative_keywords = {"лиценз"},
    },
    {
      label = "Купить оружие",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "Оружейный магазин: /price",
      keywords = {"где+купить+оружие", "купить+оружие", "оружейный+магазин", "оружие+где"},
      negative_keywords = {"лиценз", "лиц+"},
    },
    {
      label = "Крафт оружия /makegun",
      enabled = true,
      match = "contains",
      priority = 29,
      skip_if_report_id = true,
      action = "reply",
      reply = "Крафт оружия: /makegun",
      keywords = {"крафт+оруж", "крафт+ствол", "makegun", "ганы+крафт", "как+крафтить"},
    },
    {
      label = "Лицензия — где",
      enabled = true,
      match = "contains",
      priority = 33,
      skip_if_report_id = true,
      action = "reply",
      reply = "/liclist",
      keywords = {"лицензия+оружие", "лиц+на+оружие", "как+получить+лицензию", "лицензия+где", "лиц+оружие", "где+лиценз", "лицензии+получ", "лицензию+оруж", "взять+лицензию+оружие", "купить+лицензию+оружие"},
    },
    {
      label = "Список лицензеров",
      enabled = true,
      match = "contains",
      priority = 28,
      skip_if_report_id = true,
      action = "reply",
      reply = "Список лицензеров: /liclist",
      keywords = {"liclist", "список+лицензер", "кто+лицензер", "где+лицензии+получ", "лицензии+получают"},
    },
    {
      label = "Скиллы /skill",
      enabled = true,
      match = "contains",
      priority = 35,
      skip_if_report_id = true,
      action = "reply",
      reply = "/skill",
      keywords = {"посмотреть+скиллы", "как+смотреть+скилл", "свои+навыки", "где+скилл", "/skill", "скилы", "скиллы", "чекнуть+скилл", "навыки+оруж", "владения+оруж", "прокачивать+скилл", "прокачивать+навыки", "продвинут+навык", "как+качать+скилл"},
      negative_keywords = {"где+тир", "тир+gps", "gps+тир", "в+тире"},
    },
    {
      label = "Сброс /reset",
      enabled = true,
      match = "contains",
      priority = 31,
      skip_if_report_id = true,
      action = "reply",
      reply = "Сброс анимации/предмета: /reset или нажмите Enter",
      keywords = {"убрать+анимку", "отключить+анимацию", "анимация+убрать", "застрял+аним", "анимка", "/anim", "застрял+в+аним", "логотип+спин", "убрать+логотип", "кейс+рук", "легендарный+кейс", "убрать+кейс"},
    },
    {
      label = "Спортзал /end",
      enabled = true,
      match = "contains",
      priority = 31,
      skip_if_report_id = true,
      action = "reply",
      reply = "Выйти из спортзала / снять форму: /reset /end",
      keywords = {"спортзал", "снять+форму+спорт", "переодеть+спорт", "заниматься+зале", "перестать+заниматься", "выйти+зал", "перестать+заниматься+зале"},
    },
    {
      label = "Инвентарь /i",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "/i (редактировать: /i edit)",
      keywords = {"инвентарь", "как+инвентарь", "как+открыть+инвентарь", "открыть+инвентарь", "где+инвентарь", "аксессуар", "снять+аксессуар", "надпись+спин", "edit", "зайти+инвентарь"},
      negative_keywords = {"донат", "пополн", "advance+credit", "advance+credits", "кредит", "credits", "скин", "валют", "банкомат"},
    },
    {
      label = "Чат организации /r /f",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "Чат организации/фракции: /r /f",
      keywords = {"чат+фракции", "чат+орги", "как+писать+в+фракцию", "чат+организа", "писать+организа", "как+писать+организа"},
    },
    {
      label = "Нон-РП чат /fn",
      enabled = true,
      match = "contains",
      priority = 29,
      skip_if_report_id = true,
      action = "reply",
      reply = "Нон-РП чат фракции: /fn",
      keywords = {"нрп+чат", "нон+рп+чат"},
    },
    {
      label = "Чат банды /rn",
      enabled = true,
      match = "contains",
      priority = 28,
      skip_if_report_id = true,
      action = "reply",
      reply = "Чат банды: /rn",
      keywords = {"чат+банды"},
    },
    {
      label = "Семейный чат /fm",
      enabled = true,
      match = "contains",
      priority = 27,
      skip_if_report_id = true,
      action = "reply",
      reply = "Семейный чат: /fm",
      keywords = {"семейный+чат", "чат+семь", "семья+чат"},
    },
    {
      label = "Список замов /zamlist",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "Список заместителей: /zamlist",
      keywords = {"список+замов", "zamlist", "замы+фракции", "кто+замы", "зам+список", "соединить+зам", "онлайн+замов", "замов+онлайн"},
    },
    {
      label = "Онлайн фракции /find",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "Участники онлайн: /find (полный список: /showall)",
      keywords = {"кто+в+сети+орги", "участники+онлайн", "онлайн+фракции", "члены+онлайн", "кто+в+сети+фракции", "сколько+людей+организа"},
      negative_keywords = {"бп", "battle", "батл"},
    },
    {
      label = "Полный список /showall",
      enabled = true,
      match = "contains",
      priority = 24,
      skip_if_report_id = true,
      action = "reply",
      reply = "Полный список фракции: /showall",
      keywords = {"полный+список", "showall", "все+участники", "список+фракции"},
      negative_keywords = {"бп", "battle", "батл"},
    },
    {
      label = "Звёзды розыска",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "Снять звёзды: сдайтесь в полицейском участке",
      keywords = {"снять+звезды", "убрать+звезды", "звезды+розыска", "как+снять+розыск", "розыск+как+снять", "сбросить+розыск", "розыск+снять", "как+розыск+снять"},
    },
    {
      label = "Бензин/АЗС",
      enabled = true,
      match = "contains",
      priority = 36,
      skip_if_report_id = true,
      action = "reply",
      reply = "Канистра на АЗС; залить в бак: /getfuel на заправке",
      keywords = {"нет+бензина", "кончился+бензин", "нет+топлива", "бензин+кончился", "азс+где", "канистр", "купить+канистр", "где+азс", "купить+бензин", "купить+топлив", "не+могу+купить+топлив", "getfuel", "заправить+машин", "топлив+машин", "купить+топлив+машин", "залить+бензин"},
      negative_keywords = {"запрос+игрок", "контракт", "механик"},
    },
    {
      label = "Механик /c 090",
      enabled = true,
      match = "contains",
      priority = 36,
      skip_if_report_id = true,
      action = "reply",
      reply = "Вызвать механика: /c 090",
      keywords = {"вызвать+механика", "механик+номер", "/c 090", "как+вызвать+механика", "эвакуатор", "вызвать+механиков", "позвать+механика"},
      negative_keywords = {"квест+механик", "заклад", "участок", "квест"},
    },
    {
      label = "Ремкомплект /fix",
      enabled = true,
      match = "contains",
      priority = 32,
      skip_if_report_id = true,
      action = "reply",
      reply = "Использовать ремкомплект: /fix",
      keywords = {"ремкомплект", "рем+комплект", "как+ремкомплект", "воспользоваться+рем", "repair+kit"},
    },
    {
      label = "Аренда транспорта",
      enabled = true,
      match = "contains",
      priority = 34,
      skip_if_report_id = true,
      action = "reply",
      reply = "Отменить аренду / убрать транспорт: /unrent или /x",
      keywords = {"арендовал+скутер", "аренда+транспорт", "unrent", "на+крыше+заспавн", "арендован"},
    },
    {
      label = "Батл Пасс /bp",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "/bp",
      keywords = {"батл+пасс", "battle+pass", "баттл+пасс", "/bp", "что+такое+бп", "команда+bp", "battlepass"},
      negative_keywords = {"квест", "ключ", "машин", "отель", "голод", "нарко", "drugs", "zamlist", "замов", "jailbreak", "тюрьм", "дом+номер", "members", "бургер", "find", "showall", "allow", "передать", "организа", "online+зам"},
    },
    {
      label = "Прогресс БП /tasks",
      enabled = true,
      match = "contains",
      priority = 24,
      skip_if_report_id = true,
      action = "reply",
      reply = "/tasks",
      keywords = {"задания+бп", "прогресс+бп", "задания+bp", "/tasks", "ежедневн+задан", "сезонн+задан", "battle+pass+задан", "задания+battle"},
      negative_keywords = {"пицц", "автобус+квест", "квест+автоб", "трамвай", "рельс", "фбр", "маяк", "разvozk", "квест+телефон", "помогите+квест", "квест+помог", "квест+пицц", "квест+автобус"},
    },
    {
      label = "Advance Credits — help",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "Advance Credits: /creditshelp",
      keywords = {"адванс+кредиты", "advance+credits", "creditshelp", "кредиты+как+использовать", "адванс+кредит", "меню+кредит", "адванс+credits", "тратить+адванс", "юзать+кредит", "где+взять+адванс"},
      negative_keywords = {"сколько+кредит", "баланс+кредит", "чекнуть+адванс", "сколько+адванс", "инвентарь", "скин", "взять+кредит", "банк+кредит", "кредит+банк", "ипотек"},
    },
    {
      label = "Баланс кредитов /st",
      enabled = true,
      match = "contains",
      priority = 19,
      skip_if_report_id = true,
      action = "reply",
      reply = "/mn 1",
      keywords = {"баланс+кредит", "сколько+кредит", "кредит+баланс", "сколько+адванс+кредит", "чекнуть+адванс+кредит", "сколько+advance+credits"},
    },
    {
      label = "Магазины /price",
      enabled = true,
      match = "contains",
      priority = 26,
      skip_if_report_id = true,
      action = "reply",
      reply = "/price",
      keywords = {"/price", "price+магаз", "список+магаз", "магазин+price", "автосалон", "пиротехник", "салют", "24+7", "где+магазин", "price+список", "магазин+одежд", "парикмахер"},
      negative_keywords = {"оружие", "телефон", "отель", "лиценз", "инфернус", "катан", "сидj", "сидж", "зарабат", "дом+купить", "аксы", "аксессуар", "спин", "катана", "заработать"},
    },
    {
      label = "Отмычка",
      enabled = true,
      match = "contains",
      priority = 27,
      skip_if_report_id = true,
      action = "reply",
      reply = "Отмычка: /price — магазин игрушек",
      keywords = {"отмычк", "взлом+машин", "купить+отмыч", "где+отмыч", "преобрести+отмыч"},
    },
    {
      label = "Продать SIM /sellsim",
      enabled = true,
      match = "contains",
      priority = 28,
      skip_if_report_id = true,
      action = "reply",
      reply = "Продать SIM-карту: /sellsim (в салоне связи)",
      keywords = {"продать+сим", "sellsim", "симк+прод", "симку+чел"},
    },
    {
      label = "Адвокат /adlist",
      enabled = true,
      match = "contains",
      priority = 33,
      skip_if_report_id = true,
      action = "reply",
      reply = "Список адвокатов: /adlist",
      keywords = {"вызвать+адвокат", "адвокат+номер", "adlist", "список+адвокат", "как+адвокат", "визвать+адвокат"},
    },
    {
      label = "Выпустить из тюрьмы /free",
      enabled = true,
      match = "contains",
      priority = 32,
      skip_if_report_id = true,
      action = "reply",
      reply = "Выпустить игрока (адвокат): /free [id]",
      keywords = {"выпустить+тюрьм", "выпустить+адвокат", "free+id", "из+тюрьмы+адвокат"},
    },
    {
      label = "Спавн точка /setspawn",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "Сменить место спавна: /setspawn",
      keywords = {"место+спавна", "setspawn", "сменить+спавн", "поменять+спавн", "спавн+орга", "изменить+спавн", "точка+спавна", "выбрать+место+спауна", "как+выбрать+спавн"},
    },
    {
      label = "Подать объявление /ad",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "Подать объявление: /ad [текст]",
      keywords = {"как+подать+объявление", "подать+объявление", "/ad", "объявление+команда", "объявление", "обьявление", "инфернус+купить", "купить+инфернус"},
    },
    {
      label = "Позвонить /c",
      enabled = true,
      match = "contains",
      priority = 22,
      skip_if_report_id = true,
      action = "reply",
      reply = "Позвонить: /c [номер]",
      keywords = {"как+позвонить", "позвонить+игроку", "как+звонить", "говорить+телефон", "номер+телефон"},
      negative_keywords = {"такси", "555"},
    },
    {
      label = "Купить телефон",
      enabled = true,
      match = "contains",
      priority = 21,
      skip_if_report_id = true,
      action = "reply",
      reply = "Телефон — в магазине 24/7 (/price)",
      keywords = {"купить+телефон", "телефон+где", "где+телефон", "нет+телефона"},
      negative_keywords = {"квест+телефон"},
    },
    {
      label = "Микрофон (войс)",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "/voice, F2; настройки F9",
      keywords = {"включить+микрофон", "войс+чат", "микрофон+как", "f2+микро", "voice+chat", "не+работает+микро", "войсом+пользов", "голосовой+чат", "как+говорить+войс", "забиндить+войс", "клавиша+войс"},
    },
    {
      label = "Варн инфо /warninfo",
      enabled = true,
      match = "contains",
      priority = 15,
      skip_if_report_id = true,
      action = "reply",
      reply = "Информация о предупреждениях: /warninfo",
      keywords = {"сколько+варнов", "мои+варны", "warninfo", "варн+инфо", "срок+варна"},
    },
    {
      label = "Лицензии /lic",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "Показать свои лицензии: /lic",
      keywords = {"показать+лицензии", "мои+лицензии", "/lic", "лицензии+команда", "как+показать+лиц"},
      negative_keywords = {"купить+оруж", "получить+лиценз"},
    },
    {
      label = "Квест трамвай",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "Квест с трамваем: НПС у депо /gps 5, проедьте 1 круг",
      keywords = {"квест+трамвай", "трамвай+квест", "квест+трамвае", "как+сделать+трамвай", "трамвайный+квест"},
    },
    {
      label = "Загрузить металл /buym",
      enabled = true,
      match = "contains",
      priority = 26,
      skip_if_report_id = true,
      action = "reply",
      reply = "Загрузить металл: /buym на чекпоинте шахты",
      keywords = {"загрузить+металл", "металл+в+грузовик", "как+загрузить+руду", "buym", "металл+куда"},
    },
    {
      label = "GPS Шахта",
      enabled = true,
      match = "contains",
      priority = 24,
      skip_if_report_id = true,
      action = "reply",
      reply = "Шахта: /gps 5",
      keywords = {"шахта+квест", "где+шахта", "шахта+где", "шахта+gps"},
    },
    {
      label = "Макс. скорость",
      enabled = true,
      match = "contains",
      priority = 18,
      skip_if_report_id = true,
      action = "reply",
      reply = "Поднять лимит скорости (макс.): /price 22",
      keywords = {"максималка+85", "лимит+скорост", "макс+скорост", "ограничен+85", "скорост+85"},
    },
    {
      label = "Донат /donate",
      enabled = true,
      match = "contains",
      priority = 22,
      skip_if_report_id = true,
      action = "reply",
      reply = "Донат: пополнить и использовать — /donate (меню доната: /mn 12)",
      keywords = {"донат+команда", "пополнить+донат", "донат+баланс", "где+донат", "/donate", "как+задонатить", "как+использовать+донат", "пополнил+руб", "как+тратить+донат", "не+могу+донат"},
    },
    {
      label = "Покинуть фракцию /leave",
      enabled = true,
      match = "contains",
      priority = 15,
      skip_if_report_id = true,
      action = "reply",
      reply = "Покинуть организацию: /leave",
      keywords = {"выйти+из+орги", "уйти+из+фракции", "выйти+организа", "/leave", "как+уйти+из+банды", "выйти+гос"},
    },
    {
      label = "Режим таксиста",
      enabled = true,
      match = "contains",
      priority = 43,
      skip_if_report_id = true,
      action = "reply",
      reply = "Принять клиента: 2 — режим таксиста (авто, договорная и т.д.)",
      keywords = {"принять+клиента+такси", "клиент+такси", "режим+таксист"},
    },
    {
      label = "Автовокзал",
      enabled = true,
      match = "contains",
      priority = 28,
      skip_if_report_id = true,
      action = "reply",
      reply = "Стоянка автобусов: на автовокзале",
      keywords = {"стоянка+автобус", "автовокзал", "где+автобус+стоян"},
    },
    {
      label = "Директор завода",
      enabled = true,
      match = "contains",
      priority = 22,
      skip_if_report_id = true,
      action = "reply",
      reply = "Директор завода: внутри завода, -1 этаж",
      keywords = {"директор+завод", "где+директор+завод"},
    },
    {
      label = "Полноэкранный режим",
      enabled = true,
      match = "contains",
      priority = 10,
      skip_if_report_id = true,
      action = "reply",
      reply = "Полноэкранный / оконный режим: Alt + Enter",
      keywords = {"полноэкранный", "полный+экран", "оконный+режим", "alt+enter", "как+сделать+полный+экран"},
    },
    {
      label = "GPS Нефтезавод",
      enabled = true,
      match = "contains",
      priority = 27,
      skip_if_report_id = true,
      action = "reply",
      reply = "/gps 5 нефтезавод",
      keywords = {"топлив+загруз", "загрузить+топлив", "топлив+завод", "нефтезавод", "топлив+привез", "где+топлив+загруз"},
      negative_keywords = {"getfuel", "азс", "канистр", "заправ", "механик"},
    },
    {
      label = "GPS / метки",
      enabled = true,
      match = "contains",
      priority = 23,
      skip_if_report_id = true,
      action = "reply",
      reply = "/gps",
      keywords = {"убрать+метку", "бесполезн+метк", "метк+gps", "как+gps", "ближайший+24", "лишн+метк"},
      negative_keywords = {"поезд", "автосалон", "султан", "мэри", "правительств"},
    },
  },
}
