-- Admin Report Desk user settings (UTF-8)
-- report-desk-user-config: utf-8
-- Scenarios. Auto-reply keywords are built-in; edit toggles/text in Report Desk settings.
return {
  strings = {
    gg_reply = "Хорошей игры на ARP Blue)",
    tech_reply = "Лучше обратитесь в технический раздел на форуме ARP",
    watch_notify = "see",
  },
  composer_quick_buttons = {
    {
      id = "gg",
      label = "GG",
      text = "Хорошей игры на ARP Blue)",
    },
    {
      id = "tech",
      label = "Техничка",
      text = "Лучше обратитесь в технический раздел на форуме ARP",
    },
  },
  scenarios_pack_version = 2,
  quick_scenarios = {
    {
      label = "GPS Тир",
      enabled = true,
      match = "contains",
      priority = 42,
      skip_if_report_id = true,
      action = "reply",
      reply = "/gps 7-2",
      keywords = {"где+тир", "тир+gps", "gps+тир", "стрелковый+тир", "как+попасть+тир", "найти+тир", "тир+где", "тир+сан", "навыки+оруж", "владения+оруж", "прокачивать+скилл", "как+качать+скилл", "где+качать+скилл", "прокачать+навыки"},
    },
    {
      label = "GPS Транспортная",
      enabled = true,
      match = "contains",
      priority = 35,
      skip_if_report_id = true,
      action = "reply",
      reply = "/gps 9",
      keywords = {"транспортная+компания", "дальнобойщик", "работ+дальноб", "найти+работу+дальноб", "где+дальноб", "gps+транспорт", "дальнобой+gps", "работа+дальнобой", "устроиться+транспорт", "дальнобоем+работать"},
    },
    {
      label = "GPS Военкомат ЛВ",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "/gps 1 7",
      keywords = {"военкомат", "воинкомат", "военком", "военкомат+лв", "военкомат+гпс"},
    },
    {
      label = "Найти отель",
      enabled = true,
      match = "contains",
      priority = 50,
      skip_if_report_id = true,
      action = "reply",
      reply = "/price",
      keywords = {"где+отель", "как+найти+отель", "отель+gps", "найти+отель", "гостиница+где", "куда+заселиться", "как+посмотреть+отель"},
      negative_keywords = {"собес"},
    },
    {
      label = "Слёт номера отеля",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "Номера отелей слетают около 00:03",
      keywords = {"слетают+номер", "слетают+отел", "во+сколько+отел", "слетают+номера", "слет+отел", "сколько+слетают+отел"},
      negative_keywords = {"найти+отель", "где+отель", "купить+отель"},
    },
    {
      label = "Слить авто в гос",
      enabled = true,
      match = "contains",
      priority = 35,
      skip_if_report_id = true,
      action = "reply",
      reply = "на рецепшене отеля сдайте авто в гос",
      keywords = {"слить+авто+гос", "слить+машину+гос", "слить+тачку+гос", "продать+авто+гос", "продать+машину+гос", "сдать+авто+гос", "сдать+в+гос", "слить+в+гос", "тачку+в+гос", "машину+вгос", "продать+гос", "слить+авто+госс", "слить+машину+госс", "тачку+в+госс"},
    },
    {
      label = "Найти свою машину",
      enabled = true,
      match = "contains",
      priority = 42,
      skip_if_report_id = true,
      action = "reply",
      reply = "/home /hotel",
      keywords = {"где+моя+машина", "где+мой+авто", "купил+машину+где", "машина+где", "заспавнить+авто", "заспавнить+машин", "спавн+машин", "заспавнить+машину", "пропала+машин", "машина+пропала", "как+найти+машину", "купленную+машину", "заспавнить+свой+авто", "не+заспавнил", "свой+тс+вызвать", "где+стоит+машина", "найти+свою+машину"},
      negative_keywords = {"ключ", "аренд", "скутер", "unrent", "крыш", "дом"},
    },
    {
      label = "Выселиться из отеля",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "на рецепшене отеля",
      keywords = {"выселиться", "выселится", "как+выйти+из+отеля", "покинуть+отель", "выселится+отеля", "выселится+жилья"},
    },
    {
      label = "Работа в мэрии",
      enabled = true,
      match = "contains",
      priority = 44,
      skip_if_report_id = true,
      action = "reply",
      reply = "2 этаж мэрии, /gps 1",
      keywords = {"работа+мэри", "устроиться+мэри", "работу+мэри", "устроиться+на+работу+мэри", "граждан+мэри", "работа+мерии", "устроиться+мерии"},
      negative_keywords = {"автобус", "таксист"},
    },
    {
      label = "Автобусник",
      enabled = true,
      match = "contains",
      priority = 45,
      skip_if_report_id = true,
      action = "reply",
      reply = "второй этаж мэрии",
      keywords = {"водитель+автобуса", "автобусник", "автобусником", "работ+автобус", "устроиться+автобус", "работа+автобус", "где+автобусником", "водитель+автобус", "начать+автобус", "работать+автобус", "центр+занятости", "устроиться+водитель+автобус"},
    },
    {
      label = "Устроиться таксистом",
      enabled = true,
      match = "contains",
      priority = 44,
      skip_if_report_id = true,
      action = "reply",
      reply = "2 этаж мэрии, /gps 1",
      keywords = {"таксист+устроиться", "устроиться+таксист", "работа+таксист", "работать+таксист", "устроиться+таксистом", "работа+таксистом"},
      negative_keywords = {"вызвать+такси", "заказать+такси", "555"},
    },
    {
      label = "Вызвать такси",
      enabled = true,
      match = "contains",
      priority = 48,
      skip_if_report_id = true,
      action = "reply",
      reply = "/c 555",
      keywords = {"вызвать+такси", "позвать+такси", "позвонить+такси", "как+вызвать+такси", "как+позвонить+такси", "такси+вызов", "заказать+такси", "номер+такси"},
    },
    {
      label = "Анонсы /news",
      enabled = true,
      match = "contains",
      priority = 40,
      skip_if_report_id = true,
      action = "reply",
      reply = "/join /news",
      keywords = {"собеседование", "собеседован", "собес", "список+собес", "список+собеседован", "как+собес", "когда+собес", "анонс+набор", "анонс+собес", "когда+набор", "/news", "куда+собес", "посмотреть+собес"},
    },
    {
      label = "Набор /join",
      enabled = true,
      match = "contains",
      priority = 38,
      skip_if_report_id = true,
      action = "reply",
      reply = "/join",
      keywords = {"набор+в+орг", "набор+орга", "как+узнать+набор", "где+набор"},
      negative_keywords = {"собес"},
    },
    {
      label = "Запустить двигатель",
      enabled = true,
      match = "contains",
      priority = 45,
      skip_if_report_id = true,
      action = "reply",
      reply = "/e (ctrl)",
      keywords = {"запустить+двигатель", "завести+мотор", "команда+двигатель", "двигатель+команда", "как+завести", "запуск+мотора", "завести+двигатель", "транспорт+завести", "завести+транспорт"},
    },
    {
      label = "Багажник",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "/b",
      keywords = {"багажник", "как+открыть+багажник", "открыть+бак", "задний+бак"},
    },
    {
      label = "Ключи от авто /allow",
      enabled = true,
      match = "contains",
      priority = 41,
      skip_if_report_id = true,
      action = "reply",
      reply = "/allow",
      keywords = {"передать+ключ", "ключ+машин", "ключи+машин", "ключ+авто", "дать+ключ"},
    },
    {
      label = "Продать оружие",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "/sellgun",
      keywords = {"sellgun", "как+передать+оружие+игроку"},
      negative_keywords = {"лиценз", "банды", "крафт"},
    },
    {
      label = "Купить оружие",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "/price",
      keywords = {"где+купить+оружие", "купить+оружие", "оружейный+магазин", "оружие+где", "где+оружие+магаз"},
      negative_keywords = {"лиценз"},
    },
    {
      label = "Крафт оружия /makegun",
      enabled = true,
      match = "contains",
      priority = 29,
      skip_if_report_id = true,
      action = "reply",
      reply = "/makegun",
      keywords = {"крафт+оруж", "крафт+ствол", "makegun", "как+крафтить+ствол", "крафтить+ган"},
    },
    {
      label = "Лицензия — где",
      enabled = true,
      match = "contains",
      priority = 33,
      skip_if_report_id = true,
      action = "reply",
      reply = "/liclist",
      keywords = {"лицензия+оружие", "лиц+на+оружие", "как+получить+лицензию", "лицензия+где", "лиц+оружие", "где+лиценз", "лицензии+получ", "лицензию+оруж", "взять+лицензию+оружие", "купить+лицензию+оружие"},
    },
    {
      label = "Список лицензеров",
      enabled = true,
      match = "contains",
      priority = 28,
      skip_if_report_id = true,
      action = "reply",
      reply = "/liclist",
      keywords = {"liclist", "список+лицензер", "кто+лицензер", "где+лицензии+получ", "лицензии+получают"},
    },
    {
      label = "Скиллы /skill",
      enabled = true,
      match = "contains",
      priority = 35,
      skip_if_report_id = true,
      action = "reply",
      reply = "/skill",
      keywords = {"посмотреть+скиллы", "как+смотреть+скилл", "свои+навыки", "где+скилл", "/skill", "скилы", "скиллы", "чекнуть+скилл", "как+скилл+посмотреть", "скилл+игрока"},
      negative_keywords = {"где+тир", "тир+gps", "в+тире", "продвинут"},
    },
    {
      label = "Сброс /reset",
      enabled = true,
      match = "contains",
      priority = 31,
      skip_if_report_id = true,
      action = "reply",
      reply = "/reset",
      keywords = {"убрать+анимку", "отключить+анимацию", "анимация+убрать", "застрял+аним", "анимка", "/anim", "застрял+в+аним", "логотип+спин", "убрать+логотип", "кейс+рук", "легендарный+кейс", "убрать+кейс"},
    },
    {
      label = "Спортзал /end",
      enabled = true,
      match = "contains",
      priority = 31,
      skip_if_report_id = true,
      action = "reply",
      reply = "/end",
      keywords = {"спортзал", "снять+форму+спорт", "переодеть+спорт", "заниматься+зале", "перестать+заниматься", "выйти+зал", "перестать+заниматься+зале"},
    },
    {
      label = "Инвентарь /i",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "/i",
      keywords = {"инвентарь", "как+инвентарь", "как+открыть+инвентарь", "открыть+инвентарь", "где+инвентарь", "надпись+спин", "зайти+инвентарь", "снять+форму", "тут+есть+инвентарь"},
      negative_keywords = {"донат", "пополн", "кредит", "скин", "валют", "банкомат"},
    },
    {
      label = "Чат организации /r /f",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "/r /f",
      keywords = {"чат+фракции", "чат+орги", "как+писать+в+фракцию", "чат+организа", "писать+организа", "как+писать+организа"},
    },
    {
      label = "Нон-РП чат /fn",
      enabled = true,
      match = "contains",
      priority = 29,
      skip_if_report_id = true,
      action = "reply",
      reply = "/fn",
      keywords = {"нрп+чат", "нон+рп+чат"},
    },
    {
      label = "Чат банды /rn",
      enabled = true,
      match = "contains",
      priority = 28,
      skip_if_report_id = true,
      action = "reply",
      reply = "/rn",
      keywords = {"чат+банды"},
    },
    {
      label = "Семейный чат /fm",
      enabled = true,
      match = "contains",
      priority = 27,
      skip_if_report_id = true,
      action = "reply",
      reply = "/fm",
      keywords = {"семейный+чат", "чат+семь", "семья+чат"},
    },
    {
      label = "Список замов /zamlist",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "/zamlist",
      keywords = {"список+замов", "zamlist", "замы+фракции", "кто+замы", "зам+список", "онлайн+замов", "замов+онлайн", "соединить+зам"},
    },
    {
      label = "Онлайн фракции /find",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "/find",
      keywords = {"кто+в+сети+орги", "участники+онлайн", "онлайн+фракции", "члены+онлайн", "кто+в+сети+фракции", "сколько+людей+организа"},
    },
    {
      label = "Полный список /showall",
      enabled = true,
      match = "contains",
      priority = 24,
      skip_if_report_id = true,
      action = "reply",
      reply = "/showall",
      keywords = {"полный+список", "showall", "все+участники", "список+фракции"},
    },
    {
      label = "Звёзды розыска",
      enabled = true,
      match = "contains",
      priority = 30,
      skip_if_report_id = true,
      action = "reply",
      reply = "в полицейском участке сдайтесь",
      keywords = {"снять+звезды", "убрать+звезды", "звезды+розыска", "как+снять+розыск", "розыск+как+снять", "сбросить+розыск", "розыск+снять", "как+розыск+снять"},
    },
    {
      label = "Бензин/АЗС",
      enabled = true,
      match = "contains",
      priority = 36,
      skip_if_report_id = true,
      action = "reply",
      reply = "/getfuel",
      keywords = {"нет+бензина", "кончился+бензин", "нет+топлива", "бензин+кончился", "азс+где", "канистр", "купить+канистр", "где+азс", "купить+бензин", "купить+топлив", "getfuel", "заправить+машин", "топлив+машин", "залить+бензин"},
      negative_keywords = {"механик", "цистерн", "топлив+загруз"},
    },
    {
      label = "Механик /c 090",
      enabled = true,
      match = "contains",
      priority = 36,
      skip_if_report_id = true,
      action = "reply",
      reply = "/c 090",
      keywords = {"вызвать+механика", "механик+номер", "/c 090", "как+вызвать+механика", "эвакуатор", "вызвать+механиков", "позвать+механика"},
      negative_keywords = {"квест+механик"},
    },
    {
      label = "Ремкомплект /fix",
      enabled = true,
      match = "contains",
      priority = 32,
      skip_if_report_id = true,
      action = "reply",
      reply = "/fix",
      keywords = {"ремкомплект", "рем+комплект", "как+ремкомплект", "воспользоваться+рем", "repair+kit", "как+починить+машину", "починить+авто", "поченить+машину"},
    },
    {
      label = "Аренда транспорта",
      enabled = true,
      match = "contains",
      priority = 34,
      skip_if_report_id = true,
      action = "reply",
      reply = "/unrent",
      keywords = {"арендовал+скутер", "аренда+транспорт", "unrent", "на+крыше+заспавн", "арендован"},
    },
    {
      label = "Батл Пасс /bp",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "/bp",
      keywords = {"батл+пасс", "battle+pass", "баттл+пасс", "/bp", "battlepass"},
      negative_keywords = {"задан", "квест", "топ+батл"},
    },
    {
      label = "Прогресс БП /tasks",
      enabled = true,
      match = "contains",
      priority = 24,
      skip_if_report_id = true,
      action = "reply",
      reply = "/tasks",
      keywords = {"задания+бп", "прогресс+бп", "задания+bp", "/tasks", "ежедневн+задан", "сезонн+задан", "battle+pass+задан", "задания+battle", "открыть+задания+бп"},
      negative_keywords = {"квест+пицц", "квест+автобус", "квест+трамвай"},
    },
    {
      label = "Advance Credits — help",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "/creditshelp",
      keywords = {"адванс+кредиты", "advance+credits", "creditshelp", "кредиты+как+использовать", "адванс+кредит", "меню+кредит", "тратить+адванс", "юзать+кредит", "где+взять+адванс", "как+адванс+кредиты+использовать"},
      negative_keywords = {"сколько+кредит", "баланс+кредит", "ипотек"},
    },
    {
      label = "Баланс кредитов /mn 1",
      enabled = true,
      match = "contains",
      priority = 19,
      skip_if_report_id = true,
      action = "reply",
      reply = "/mn 1",
      keywords = {"баланс+кредит", "сколько+кредит", "кредит+баланс", "сколько+адванс+кредит", "чекнуть+адванс+кредит", "сколько+advance+credits", "где+посмотреть+койны"},
    },
    {
      label = "Магазины /price",
      enabled = true,
      match = "contains",
      priority = 26,
      skip_if_report_id = true,
      action = "reply",
      reply = "/price",
      keywords = {"/price", "список+магаз", "магазин+price", "пиротехник", "салют", "24+7", "где+магазин", "магазин+одежд", "парикмахер", "магазин+мебел", "где+купить+салют", "аксессуар+магаз"},
      negative_keywords = {"оружие", "телефон", "отель", "лиценз", "инфернус"},
    },
    {
      label = "Отмычка",
      enabled = true,
      match = "contains",
      priority = 27,
      skip_if_report_id = true,
      action = "reply",
      reply = "/price магазин игрушек",
      keywords = {"отмычк", "взлом+машин", "купить+отмыч", "где+отмыч", "преобрести+отмыч"},
    },
    {
      label = "Продать SIM /sellsim",
      enabled = true,
      match = "contains",
      priority = 28,
      skip_if_report_id = true,
      action = "reply",
      reply = "/sellsim",
      keywords = {"продать+сим", "sellsim", "симк+прод", "симку+чел"},
    },
    {
      label = "Адвокат /adlist",
      enabled = true,
      match = "contains",
      priority = 33,
      skip_if_report_id = true,
      action = "reply",
      reply = "/adlist",
      keywords = {"вызвать+адвокат", "адвокат+номер", "adlist", "список+адвокат", "как+адвокат", "визвать+адвокат", "адвоката+в+тюрьму"},
    },
    {
      label = "Выпустить из тюрьмы /free",
      enabled = true,
      match = "contains",
      priority = 32,
      skip_if_report_id = true,
      action = "reply",
      reply = "/free id",
      keywords = {"выпустить+тюрьм", "выпустить+адвокат", "как+выпустить+из+тюрьмы", "из+тюрьмы+адвокат"},
    },
    {
      label = "Спавн точка /setspawn",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "/setspawn",
      keywords = {"место+спавна", "setspawn", "сменить+спавн", "поменять+спавн", "спавн+орга", "изменить+спавн", "точка+спавна", "как+выбрать+спавн", "выбрать+место+спауна"},
    },
    {
      label = "Подать объявление /ad",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "/ad",
      keywords = {"как+подать+объявление", "подать+объявление", "/ad", "объявление+команда", "объявление", "обьявление", "инфернус+купить", "купить+инфернус", "как+обьявление+подать"},
    },
    {
      label = "Позвонить /c",
      enabled = true,
      match = "contains",
      priority = 22,
      skip_if_report_id = true,
      action = "reply",
      reply = "/c",
      keywords = {"как+позвонить", "позвонить+игроку", "как+звонить", "говорить+телефон", "номер+телефон", "как+разговаривать", "звонить+с+мобилки"},
      negative_keywords = {"такси", "555", "090"},
    },
    {
      label = "Купить телефон",
      enabled = true,
      match = "contains",
      priority = 21,
      skip_if_report_id = true,
      action = "reply",
      reply = "/price",
      keywords = {"купить+телефон", "телефон+где", "где+телефон", "нет+телефона"},
      negative_keywords = {"квест+телефон"},
    },
    {
      label = "Микрофон (войс)",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "F2; настройки F9",
      keywords = {"включить+микрофон", "войс+чат", "микрофон+как", "f2+микро", "voice+chat", "не+работает+микро", "войсом+пользов", "голосовой+чат", "как+говорить+войс", "забиндить+войс", "клавиша+войс", "как+говорить+в+микро", "голосовой+как"},
    },
    {
      label = "Варн инфо /warninfo",
      enabled = true,
      match = "contains",
      priority = 15,
      skip_if_report_id = true,
      action = "reply",
      reply = "/warninfo",
      keywords = {"сколько+варнов", "мои+варны", "warninfo", "варн+инфо", "срок+варна"},
    },
    {
      label = "Лицензии /lic",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "/lic",
      keywords = {"показать+лицензии", "мои+лицензии", "/lic", "лицензии+команда", "как+показать+лиц"},
      negative_keywords = {"купить+лиценз", "получить+лиценз"},
    },
    {
      label = "Квест трамвай",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "/gps 5, проедь 1 круг",
      keywords = {"квест+трамвай", "трамвай+квест", "квест+трамвае", "как+сделать+трамвай", "трамвайный+квест"},
    },
    {
      label = "Загрузить металл /buym",
      enabled = true,
      match = "contains",
      priority = 26,
      skip_if_report_id = true,
      action = "reply",
      reply = "/buym",
      keywords = {"загрузить+металл", "металл+в+грузовик", "как+загрузить+руду", "buym", "металл+куда"},
    },
    {
      label = "GPS Шахта",
      enabled = true,
      match = "contains",
      priority = 24,
      skip_if_report_id = true,
      action = "reply",
      reply = "Шахта: /gps 5",
      keywords = {"шахта+квест", "где+шахта", "шахта+где", "шахта+gps", "металл+набрать", "где+металл+для+доставки"},
      negative_keywords = {"сдать+металл", "sellm"},
    },
    {
      label = "Макс. скорость",
      enabled = true,
      match = "contains",
      priority = 18,
      skip_if_report_id = true,
      action = "reply",
      reply = "/price 22",
      keywords = {"максималка+85", "лимит+скорост", "макс+скорост", "ограничен+85", "скорост+85", "тюнинг+ателье", "где+тюнинг", "найти+тюнинг", "покраска+машин", "цвет+мото", "записался+тюнинг", "тюнинг+авто"},
    },
    {
      label = "Донат /donate",
      enabled = true,
      match = "contains",
      priority = 22,
      skip_if_report_id = true,
      action = "reply",
      reply = "/donate",
      keywords = {"донат+команда", "пополнить+донат", "донат+баланс", "где+донат", "/donate", "как+задонатить", "как+использовать+донат", "пополнил+руб", "как+тратить+донат", "не+могу+донат", "пополнила+300"},
      negative_keywords = {"обмен", "кредит", "банкомат"},
    },
    {
      label = "Покинуть фракцию /leave",
      enabled = true,
      match = "contains",
      priority = 15,
      skip_if_report_id = true,
      action = "reply",
      reply = "/leave",
      keywords = {"выйти+из+орги", "уйти+из+фракции", "выйти+организа", "/leave", "как+уйти+из+банды", "выйти+гос"},
    },
    {
      label = "Режим таксиста",
      enabled = true,
      match = "contains",
      priority = 43,
      skip_if_report_id = true,
      action = "reply",
      reply = "2",
      keywords = {"принять+клиента+такси", "клиент+такси", "режим+таксист"},
    },
    {
      label = "Автовокзал",
      enabled = true,
      match = "contains",
      priority = 28,
      skip_if_report_id = true,
      action = "reply",
      reply = "на автовокзале",
      keywords = {"стоянка+автобус", "автовокзал", "где+автобус+стоян"},
    },
    {
      label = "Директор завода",
      enabled = true,
      match = "contains",
      priority = 22,
      skip_if_report_id = true,
      action = "reply",
      reply = "-1 этаж завода",
      keywords = {"директор+завод", "где+директор+завод"},
    },
    {
      label = "Полноэкранный режим",
      enabled = true,
      match = "contains",
      priority = 10,
      skip_if_report_id = true,
      action = "reply",
      reply = "Alt+Enter",
      keywords = {"полноэкранный", "полный+экран", "оконный+режим", "alt+enter", "как+сделать+полный+экран"},
    },
    {
      label = "GPS Нефтезавод",
      enabled = true,
      match = "contains",
      priority = 27,
      skip_if_report_id = true,
      action = "reply",
      reply = "/gps 5 нефтезавод",
      keywords = {"топлив+загруз", "загрузить+топлив", "топлив+завод", "нефтезавод", "топлив+привез", "где+топлив+загруз"},
      negative_keywords = {"getfuel", "азс", "канистр", "заправ"},
    },
    {
      label = "GPS / метки",
      enabled = true,
      match = "contains",
      priority = 23,
      skip_if_report_id = true,
      action = "reply",
      reply = "/gps",
      keywords = {"убрать+метку", "бесполезн+метк", "метк+gps", "как+gps", "ближайший+24", "лишн+метк"},
      negative_keywords = {"поезд", "автосалон", "султан", "мэри", "правительств"},
    },
    {
      label = "Шептать /w",
      enabled = true,
      match = "contains",
      priority = 46,
      skip_if_report_id = true,
      action = "reply",
      reply = "/w",
      keywords = {"шептать", "шепнуть", "whisper", "/w", "как+шептать", "шепток", "написать+шепотом"},
    },
    {
      label = "Припарковать /car",
      enabled = true,
      match = "contains",
      priority = 38,
      skip_if_report_id = true,
      action = "reply",
      reply = "/car",
      keywords = {"припарковать", "/car", "парковка+машин", "поставить+машину", "припарковать+машин", "парковать+авто"},
    },
    {
      label = "Нарко /drugs",
      enabled = true,
      match = "contains",
      priority = 42,
      skip_if_report_id = true,
      action = "reply",
      reply = "/drugs",
      keywords = {"нарко", "/drugs", "команда+нарко", "как+нарко", "drugs+команда", "где+нарко", "как+юзать+нарко"},
      negative_keywords = {"почему+нарко", "рвет", "рвется", "после+нарко"},
    },
    {
      label = "Лидеры /leaders",
      enabled = true,
      match = "contains",
      priority = 26,
      skip_if_report_id = true,
      action = "reply",
      reply = "/leaders",
      keywords = {"лидеры", "/leaders", "leaders", "кто+лидер", "список+лидер", "где+лидер"},
      negative_keywords = {"заявлен", "лидерк", "форум"},
    },
    {
      label = "FPS /fpslimit",
      enabled = true,
      match = "contains",
      priority = 12,
      skip_if_report_id = true,
      action = "reply",
      reply = "/fpslimit",
      keywords = {"fpslimit", "/fpslimit", "фпс+лимит", "fps+лимит", "ограничить+фпс", "фпс+огранич"},
    },
    {
      label = "Обмен донат на кредиты",
      enabled = true,
      match = "contains",
      priority = 24,
      skip_if_report_id = true,
      action = "reply",
      reply = "только в банкомате",
      keywords = {"обменять+донат", "донат+кредит", "кредит+донат", "донат+на+кредит", "обмен+донат"},
    },
    {
      label = "Автосалон /gps 1",
      enabled = true,
      match = "contains",
      priority = 49,
      skip_if_report_id = true,
      action = "reply",
      reply = "/gps 1",
      keywords = {"автосалон", "эконом+автосалон", "автосалон+эконом", "автосалон+лс", "где+автосалон", "салон+машин", "авторынок+лс"},
      negative_keywords = {"слить", "гос"},
    },
    {
      label = "Завершить звонок /h",
      enabled = true,
      match = "contains",
      priority = 22,
      skip_if_report_id = true,
      action = "reply",
      reply = "/h",
      keywords = {"как+закончить+звонок", "завершить+звонок", "закончить+разговор", "как+закончить+разговор", "положить+трубку"},
    },
    {
      label = "Сдать металл /sellm",
      enabled = true,
      match = "contains",
      priority = 25,
      skip_if_report_id = true,
      action = "reply",
      reply = "/sellm",
      keywords = {"сдать+металл", "где+сдавать+металл", "куда+сдать+металл", "продать+металл+шахт"},
    },
    {
      label = "Список заправок /fuel",
      enabled = true,
      match = "contains",
      priority = 22,
      skip_if_report_id = true,
      action = "reply",
      reply = "/fuel",
      keywords = {"список+заправок", "заправки+цены", "где+заправки", "список+азс+цены"},
    },
    {
      label = "Квесты новичка /mn 2",
      enabled = true,
      match = "contains",
      priority = 20,
      skip_if_report_id = true,
      action = "reply",
      reply = "/mn 2",
      keywords = {"где+квест", "как+найти+квест", "квест+новичок", "квестовая+линия", "где+брать+квест", "первый+квест"},
      negative_keywords = {"пицц", "трамвай", "автобус", "шахт", "топлив"},
    },
    {
      label = "Топ сезона /season",
      enabled = true,
      match = "contains",
      priority = 22,
      skip_if_report_id = true,
      action = "reply",
      reply = "/season",
      keywords = {"топ+батлпасс", "топ+сезон", "/season", "рейтинг+сезон", "топ+бп"},
    },
    {
      label = "Слет домов / риелтор",
      enabled = true,
      match = "contains",
      priority = 22,
      skip_if_report_id = true,
      action = "reply",
      reply = "/gps 8 риелторское агентство",
      keywords = {"слет+домов", "где+смотреть+слет+домов", "риелторское+агентство", "риелтор+gps", "свободные+дома+где"},
    },
  },
}
