-- Intent catalog (UTF-8). Shipped with release; UI edits write config/report_desk_intents.lua.
return {
  version = 1,
  contexts = {
    thanks_exact = {
      "спасибо большое", "благодарю помогли", "ок понял", "спс админ вы лучший",
    },
  },
  intents = {
    {
      id = "faq.navigation.gps_7-2",
      context = "faq",
      category = "navigation",
      label = "GPS Тир",
      enabled = true,
      action = { type = "reply", text = "/gps 7-2" },
      triggers = {
        any = {
          { all = {"где", "тир"} },
          { all = {"тир", "gps"} },
          { all = {"gps", "тир"} },
          { all = {"стрелковый", "тир"} },
          { all = {"как", "попасть", "тир"} },
          { all = {"найти", "тир"} },
          { all = {"тир", "где"} },
          { all = {"тир", "сан"} },
          { all = {"навыки", "оруж"} },
          { all = {"владения", "оруж"} },
          { all = {"прокачивать", "скилл"} },
          { all = {"как", "качать", "скилл"} },
          { all = {"где", "качать", "скилл"} },
          { all = {"прокачать", "навыки"} },
        },
      },
    },
    {
      id = "faq.navigation.gps_9",
      context = "faq",
      category = "navigation",
      label = "GPS Транспортная",
      enabled = true,
      action = { type = "reply", text = "/gps 9" },
      triggers = {
        any = {
          { all = {"транспортная", "компания"} },
          { token = "дальнобойщик" },
          { all = {"работ", "дальноб"} },
          { all = {"найти", "работу", "дальноб"} },
          { all = {"где", "дальноб"} },
          { all = {"gps", "транспорт"} },
          { all = {"дальнобой", "gps"} },
          { all = {"работа", "дальнобой"} },
          { all = {"устроиться", "транспорт"} },
          { all = {"дальнобоем", "работать"} },
        },
      },
    },
    {
      id = "faq.navigation.gps_1_7",
      context = "faq",
      category = "navigation",
      label = "GPS Военкомат ЛВ",
      enabled = true,
      action = { type = "reply", text = "/gps 1 7" },
      triggers = {
        any = {
          { token = "военкомат" },
          { token = "воинкомат" },
          { token = "военком" },
          { all = {"военкомат", "лв"} },
          { all = {"военкомат", "гпс"} },
        },
      },
    },
    {
      id = "faq.navigation.price",
      context = "faq",
      category = "navigation",
      label = "Найти отель",
      enabled = true,
      action = { type = "reply", text = "/price" },
      triggers = {
        any = {
          { all = {"где", "отель"} },
          { all = {"как", "найти", "отель"} },
          { all = {"отель", "gps"} },
          { all = {"найти", "отель"} },
          { all = {"гостиница", "где"} },
          { all = {"куда", "заселиться"} },
          { all = {"как", "посмотреть", "отель"} },
          { all = {"как", "найти", "гостиницу"} },
          { all = {"как", "посмотреть", "отели"} },
          { all = {"где", "отел", "заселиться"} },
          { token = "собеседование" },
          { all = {"собеседование", "отель"} },
          { all = {"отель", "магазин"} },
          { all = {"price", "отель"} },
          { all = {"price", "отель", "магазин"} },
        },
      },
      exclusions = {
        {all = { "магазин" }, none = { "отель" } },
        {all = { "24" } },
        {all = { "еду" } },
      },
    },
    {
      id = "faq.gameplay.00_03",
      context = "faq",
      category = "gameplay",
      label = "Слёт номера отеля",
      enabled = true,
      action = { type = "reply", text = "Номера отелей слетают около 00:03" },
      triggers = {
        any = {
          { all = {"слетают", "номер"} },
          { all = {"слетают", "отел"} },
          { all = {"во", "сколько", "отел"} },
          { all = {"слетают", "номера"} },
          { all = {"слет", "отел"} },
          { all = {"сколько", "слетают", "отел"} },
        },
      },
      exclusions = {
        {all = { "найти", "отель" } },
        {all = { "где", "отель" } },
        {all = { "купить", "отель" } },
      },
    },
    {
      id = "faq.gameplay.n6",
      context = "faq",
      category = "gameplay",
      label = "Слить авто в гос",
      enabled = true,
      action = { type = "reply", text = "на рецепшене отеля сдайте авто в гос" },
      triggers = {
        any = {
          { all = {"слить", "авто", "гос"} },
          { all = {"слить", "машину", "гос"} },
          { all = {"слить", "тачку", "гос"} },
          { all = {"продать", "авто", "гос"} },
          { all = {"продать", "машину", "гос"} },
          { all = {"сдать", "авто", "гос"} },
          { all = {"сдать", "в", "гос"} },
          { all = {"слить", "в", "гос"} },
          { all = {"тачку", "в", "гос"} },
          { all = {"машину", "вгос"} },
          { all = {"продать", "гос"} },
          { all = {"слить", "авто", "госс"} },
          { all = {"слить", "машину", "госс"} },
          { all = {"тачку", "в", "госс"} },
        },
      },
    },
    {
      id = "faq.gameplay.home_hotel",
      context = "faq",
      category = "gameplay",
      label = "Найти свою машину",
      enabled = true,
      action = { type = "reply", text = "/home /hotel" },
      triggers = {
        any = {
          { all = {"где", "моя", "машина"} },
          { all = {"где", "мой", "авто"} },
          { all = {"купил", "машину", "где"} },
          { all = {"машина", "где"} },
          { all = {"заспавнить", "авто"} },
          { all = {"заспавнить", "машин"} },
          { all = {"спавн", "машин"} },
          { all = {"заспавнить", "машину"} },
          { all = {"пропала", "машин"} },
          { all = {"машина", "пропала"} },
          { all = {"как", "найти", "машину"} },
          { all = {"купленную", "машину"} },
          { all = {"заспавнить", "свой", "авто"} },
          { all = {"не", "заспавнил"} },
          { all = {"свой", "тс", "вызвать"} },
          { all = {"где", "стоит", "машина"} },
          { all = {"найти", "свою", "машину"} },
          { all = {"заспавнить", "тачку"} },
          { all = {"не", "могу", "заспавнить"} },
        },
      },
      exclusions = {
        {all = { "аренд" } },
      },
    },
    {
      id = "faq.gameplay.n8",
      context = "faq",
      category = "gameplay",
      label = "Выселиться из отеля",
      enabled = true,
      action = { type = "reply", text = "на рецепшене отеля" },
      triggers = {
        any = {
          { token = "выселиться" },
          { token = "выселится" },
          { all = {"как", "выйти", "из", "отеля"} },
          { all = {"покинуть", "отель"} },
          { all = {"выселится", "отеля"} },
          { all = {"выселится", "жилья"} },
        },
      },
    },
    {
      id = "faq.gameplay.2_gps_1",
      context = "faq",
      category = "gameplay",
      label = "Работа в мэрии",
      enabled = true,
      action = { type = "reply", text = "2 этаж мэрии, /gps 1" },
      triggers = {
        any = {
          { all = {"работа", "мэри"} },
          { all = {"устроиться", "мэри"} },
          { all = {"работу", "мэри"} },
          { all = {"устроиться", "на", "работу", "мэри"} },
          { all = {"граждан", "мэри"} },
          { all = {"работа", "мерии"} },
          { all = {"устроиться", "мерии"} },
        },
      },
      exclusions = {
        { },
        { },
      },
    },
    {
      id = "faq.gameplay.n10",
      context = "faq",
      category = "gameplay",
      label = "Автобусник",
      enabled = true,
      action = { type = "reply", text = "второй этаж мэрии" },
      triggers = {
        any = {
          { all = {"водитель", "автобуса"} },
          { token = "автобусник" },
          { token = "автобусником" },
          { all = {"работ", "автобус"} },
          { all = {"устроиться", "автобус"} },
          { all = {"работа", "автобус"} },
          { all = {"где", "автобусником"} },
          { all = {"водитель", "автобус"} },
          { all = {"начать", "автобус"} },
          { all = {"работать", "автобус"} },
          { all = {"центр", "занятости"} },
          { all = {"устроиться", "водитель", "автобус"} },
        },
      },
    },
    {
      id = "faq.communication.2_gps_1",
      context = "faq",
      category = "communication",
      label = "Устроиться таксистом",
      enabled = true,
      action = { type = "reply", text = "2 этаж мэрии, /gps 1" },
      triggers = {
        any = {
          { all = {"таксист", "устроиться"} },
          { all = {"устроиться", "таксист"} },
          { all = {"работа", "таксист"} },
          { all = {"работать", "таксист"} },
          { all = {"устроиться", "таксистом"} },
          { all = {"работа", "таксистом"} },
        },
      },
      exclusions = {
        {all = { "вызвать", "такси" } },
        {all = { "заказать", "такси" } },
        { },
      },
    },
    {
      id = "faq.communication.c_555",
      context = "faq",
      category = "communication",
      label = "Вызвать такси",
      enabled = true,
      action = { type = "reply", text = "/c 555" },
      triggers = {
        any = {
          { all = {"вызвать", "такси"} },
          { all = {"позвать", "такси"} },
          { all = {"позвонить", "такси"} },
          { all = {"как", "вызвать", "такси"} },
          { all = {"как", "позвонить", "такси"} },
          { all = {"такси", "вызов"} },
          { all = {"заказать", "такси"} },
          { all = {"номер", "такси"} },
        },
      },
    },
    {
      id = "faq.gameplay.join_news",
      context = "faq",
      category = "gameplay",
      label = "Анонсы /news",
      enabled = true,
      action = { type = "reply", text = "/join /news" },
      triggers = {
        any = {
          { token = "собеседование" },
          { token = "собеседован" },
          { token = "собес" },
          { all = {"список", "собес"} },
          { all = {"список", "собеседован"} },
          { all = {"как", "собес"} },
          { all = {"когда", "собес"} },
          { all = {"анонс", "набор"} },
          { all = {"анонс", "собес"} },
          { all = {"когда", "набор"} },
          { token = "/news" },
          { all = {"куда", "собес"} },
          { all = {"посмотреть", "собес"} },
          { all = {"подписаться", "новости"} },
          { all = {"news", "анонс"} },
        },
      },
      exclusions = {
        {all = { "отель" } },
        {all = { "заселиться" } },
      },
    },
    {
      id = "faq.gameplay.join",
      context = "faq",
      category = "gameplay",
      label = "Набор /join",
      enabled = true,
      action = { type = "reply", text = "/join" },
      triggers = {
        any = {
          { all = {"набор", "в", "орг"} },
          { all = {"набор", "орга"} },
          { all = {"как", "узнать", "набор"} },
          { all = {"где", "набор"} },
        },
      },
      exclusions = {
        { },
      },
    },
    {
      id = "faq.gameplay.e_ctrl",
      context = "faq",
      category = "gameplay",
      label = "Запустить двигатель",
      enabled = true,
      action = { type = "reply", text = "/e (ctrl)" },
      triggers = {
        any = {
          { all = {"запустить", "двигатель"} },
          { all = {"завести", "мотор"} },
          { all = {"команда", "двигатель"} },
          { all = {"двигатель", "команда"} },
          { all = {"как", "завести"} },
          { all = {"запуск", "мотора"} },
          { all = {"завести", "двигатель"} },
          { all = {"транспорт", "завести"} },
          { all = {"завести", "транспорт"} },
        },
      },
    },
    {
      id = "faq.gameplay.b",
      context = "faq",
      category = "gameplay",
      label = "Багажник",
      enabled = true,
      action = { type = "reply", text = "/b" },
      triggers = {
        any = {
          { token = "багажник" },
          { all = {"как", "открыть", "багажник"} },
          { all = {"открыть", "бак"} },
          { all = {"задний", "бак"} },
        },
      },
    },
    {
      id = "faq.gameplay.allow",
      context = "faq",
      category = "gameplay",
      label = "Ключи от авто /allow",
      enabled = true,
      action = { type = "reply", text = "/allow" },
      triggers = {
        any = {
          { all = {"передать", "ключ"} },
          { all = {"ключ", "машин"} },
          { all = {"ключи", "машин"} },
          { all = {"ключ", "авто"} },
          { all = {"дать", "ключ"} },
        },
      },
    },
    {
      id = "faq.gameplay.sellgun",
      context = "faq",
      category = "gameplay",
      label = "Продать оружие",
      enabled = true,
      action = { type = "reply", text = "/sellgun" },
      triggers = {
        any = {
          { token = "sellgun" },
          { all = {"как", "передать", "оружие", "игроку"} },
        },
      },
      exclusions = {
        { },
        { },
        { },
      },
    },
    {
      id = "faq.gameplay.price",
      context = "faq",
      category = "gameplay",
      label = "Купить оружие",
      enabled = true,
      action = { type = "reply", text = "/price" },
      triggers = {
        any = {
          { all = {"где", "купить", "оружие"} },
          { all = {"купить", "оружие"} },
          { all = {"оружейный", "магазин"} },
          { all = {"оружие", "где"} },
          { all = {"где", "оружие", "магаз"} },
        },
      },
      exclusions = {
        { },
      },
    },
    {
      id = "faq.gameplay.makegun",
      context = "faq",
      category = "gameplay",
      label = "Крафт оружия /makegun",
      enabled = true,
      action = { type = "reply", text = "/makegun" },
      triggers = {
        any = {
          { all = {"крафт", "оруж"} },
          { all = {"крафт", "ствол"} },
          { token = "makegun" },
          { all = {"как", "крафтить", "ствол"} },
          { all = {"крафтить", "ган"} },
        },
      },
    },
    {
      id = "faq.gameplay.liclist",
      context = "faq",
      category = "gameplay",
      label = "Лицензия — где",
      enabled = true,
      action = { type = "reply", text = "/liclist" },
      triggers = {
        any = {
          { all = {"лицензия", "оружие"} },
          { all = {"лиц", "на", "оружие"} },
          { all = {"как", "получить", "лицензию"} },
          { all = {"лицензия", "где"} },
          { all = {"лиц", "оружие"} },
          { all = {"где", "лиценз"} },
          { all = {"лицензии", "получ"} },
          { all = {"лицензию", "оруж"} },
          { all = {"взять", "лицензию", "оружие"} },
        },
      },
      exclusions = {
        {all = { "список", "лицензер" } },
        {all = { "liclist" } },
      },
    },
    {
      id = "faq.navigation.liclist",
      context = "faq",
      category = "navigation",
      label = "Список лицензеров",
      enabled = true,
      action = { type = "reply", text = "/liclist" },
      triggers = {
        any = {
          { token = "liclist" },
          { all = {"список", "лицензер"} },
          { all = {"кто", "лицензер"} },
          { all = {"где", "лицензии", "получ"} },
          { all = {"лицензии", "получают"} },
          { all = {"купить", "лицензию", "оружие"} },
          { all = {"где", "купить", "лицензию"} },
          { all = {"кому", "идти", "лиценз"} },
          { all = {"где", "получить", "лицензию", "авто"} },
        },
      },
      exclusions = {
        {all = { "показать", "лиценз" } },
        {all = { "мои", "лиценз" } },
      },
    },
    {
      id = "faq.gameplay.skill",
      context = "faq",
      category = "gameplay",
      label = "Скиллы /skill",
      enabled = true,
      action = { type = "reply", text = "/skill" },
      triggers = {
        any = {
          { all = {"посмотреть", "скиллы"} },
          { all = {"как", "смотреть", "скилл"} },
          { all = {"свои", "навыки"} },
          { all = {"где", "скилл"} },
          { token = "/skill" },
          { token = "скилы" },
          { token = "скиллы" },
          { all = {"чекнуть", "скилл"} },
          { all = {"как", "скилл", "посмотреть"} },
          { all = {"скилл", "игрока"} },
        },
      },
      exclusions = {
        {all = { "где", "тир" } },
        {all = { "тир", "gps" } },
        {all = { "в", "тире" } },
        { },
      },
    },
    {
      id = "faq.gameplay.reset",
      context = "faq",
      category = "gameplay",
      label = "Сброс /reset",
      enabled = true,
      action = { type = "reply", text = "/reset" },
      triggers = {
        any = {
          { all = {"убрать", "анимку"} },
          { all = {"отключить", "анимацию"} },
          { all = {"анимация", "убрать"} },
          { all = {"застрял", "аним"} },
          { token = "анимка" },
          { token = "/anim" },
          { all = {"застрял", "в", "аним"} },
          { all = {"логотип", "спин"} },
          { all = {"убрать", "логотип"} },
          { all = {"кейс", "рук"} },
          { all = {"легендарный", "кейс"} },
          { all = {"убрать", "кейс"} },
        },
      },
    },
    {
      id = "faq.gameplay.end",
      context = "faq",
      category = "gameplay",
      label = "Спортзал /end",
      enabled = true,
      action = { type = "reply", text = "/end" },
      triggers = {
        any = {
          { token = "спортзал" },
          { all = {"снять", "форму", "спорт"} },
          { all = {"переодеть", "спорт"} },
          { all = {"заниматься", "зале"} },
          { all = {"перестать", "заниматься"} },
          { all = {"выйти", "зал"} },
          { all = {"перестать", "заниматься", "зале"} },
        },
      },
    },
    {
      id = "faq.gameplay.i",
      context = "faq",
      category = "gameplay",
      label = "Инвентарь /i",
      enabled = true,
      action = { type = "reply", text = "/i" },
      triggers = {
        any = {
          { token = "инвентарь" },
          { all = {"открыть", "инвентарь", "команд"} },
          { all = {"как", "инвентарь"} },
          { all = {"как", "открыть", "инвентарь"} },
          { all = {"открыть", "инвентарь"} },
          { all = {"где", "инвентарь"} },
          { all = {"надпись", "спин"} },
          { all = {"зайти", "инвентарь"} },
          { all = {"снять", "форму"} },
          { all = {"тут", "есть", "инвентарь"} },
        },
      },
      exclusions = {
        { },
        { },
        { },
        { },
        { },
        { },
      },
    },
    {
      id = "faq.gameplay.r_f",
      context = "faq",
      category = "gameplay",
      label = "Чат организации /r /f",
      enabled = true,
      action = { type = "reply", text = "/r /f" },
      triggers = {
        any = {
          { all = {"чат", "фракции"} },
          { all = {"чат", "орги"} },
          { all = {"как", "писать", "в", "фракцию"} },
          { all = {"чат", "организа"} },
          { all = {"писать", "организа"} },
          { all = {"как", "писать", "организа"} },
          { all = {"чат", "фракции", "команд"} },
        },
      },
    },
    {
      id = "faq.gameplay.fn",
      context = "faq",
      category = "gameplay",
      label = "Нон-РП чат /fn",
      enabled = true,
      action = { type = "reply", text = "/fn" },
      triggers = {
        any = {
          { all = {"нрп", "чат"} },
          { all = {"нон", "рп", "чат"} },
        },
      },
    },
    {
      id = "faq.gameplay.rn",
      context = "faq",
      category = "gameplay",
      label = "Чат банды /rn",
      enabled = true,
      action = { type = "reply", text = "/rn" },
      triggers = {
        any = {
          { all = {"чат", "банды"} },
        },
      },
    },
    {
      id = "faq.gameplay.fm",
      context = "faq",
      category = "gameplay",
      label = "Семейный чат /fm",
      enabled = true,
      action = { type = "reply", text = "/fm" },
      triggers = {
        any = {
          { all = {"семейный", "чат"} },
          { all = {"чат", "семь"} },
          { all = {"семья", "чат"} },
        },
      },
    },
    {
      id = "faq.gameplay.zamlist",
      context = "faq",
      category = "gameplay",
      label = "Список замов /zamlist",
      enabled = true,
      action = { type = "reply", text = "/zamlist" },
      triggers = {
        any = {
          { all = {"список", "замов"} },
          { token = "zamlist" },
          { all = {"замы", "фракции"} },
          { all = {"кто", "замы"} },
          { all = {"зам", "список"} },
          { all = {"онлайн", "замов"} },
          { all = {"замов", "онлайн"} },
          { all = {"соединить", "зам"} },
        },
      },
    },
    {
      id = "faq.gameplay.find",
      context = "faq",
      category = "gameplay",
      label = "Онлайн фракции /find",
      enabled = true,
      action = { type = "reply", text = "/find" },
      triggers = {
        any = {
          { all = {"кто", "в", "сети", "орги"} },
          { all = {"участники", "онлайн"} },
          { all = {"онлайн", "фракции"} },
          { all = {"члены", "онлайн"} },
          { all = {"кто", "в", "сети", "фракции"} },
          { all = {"сколько", "людей", "организа"} },
        },
      },
    },
    {
      id = "faq.gameplay.showall",
      context = "faq",
      category = "gameplay",
      label = "Полный список /showall",
      enabled = true,
      action = { type = "reply", text = "/showall" },
      triggers = {
        any = {
          { all = {"полный", "список"} },
          { token = "showall" },
          { all = {"все", "участники"} },
          { all = {"список", "фракции"} },
        },
      },
    },
    {
      id = "faq.gameplay.n34",
      context = "faq",
      category = "gameplay",
      label = "Звёзды розыска",
      enabled = true,
      action = { type = "reply", text = "в полицейском участке сдайтесь" },
      triggers = {
        any = {
          { all = {"снять", "звезды"} },
          { all = {"убрать", "звезды"} },
          { all = {"звезды", "розыска"} },
          { all = {"как", "снять", "розыск"} },
          { all = {"розыск", "как", "снять"} },
          { all = {"сбросить", "розыск"} },
          { all = {"розыск", "снять"} },
          { all = {"как", "розыск", "снять"} },
        },
      },
    },
    {
      id = "faq.gameplay.getfuel",
      context = "faq",
      category = "gameplay",
      label = "Бензин/АЗС",
      enabled = true,
      action = { type = "reply", text = "/getfuel" },
      triggers = {
        any = {
          { all = {"нет", "бензина"} },
          { all = {"кончился", "бензин"} },
          { all = {"нет", "топлива"} },
          { all = {"бензин", "кончился"} },
          { all = {"азс", "где"} },
          { token = "канистр" },
          { all = {"купить", "канистр"} },
          { all = {"где", "азс"} },
          { all = {"купить", "бензин"} },
          { all = {"купить", "топлив"} },
          { token = "getfuel" },
          { all = {"заправить", "машин"} },
          { all = {"топлив", "машин"} },
          { all = {"залить", "бензин"} },
        },
      },
      exclusions = {
        { },
        { },
        {all = { "топлив", "загруз" } },
      },
    },
    {
      id = "faq.communication.c_090",
      context = "faq",
      category = "communication",
      label = "Механик /c 090",
      enabled = true,
      action = { type = "reply", text = "/c 090" },
      triggers = {
        any = {
          { all = {"вызвать", "механика"} },
          { all = {"механик", "номер"} },
          { all = {"/c", "090"} },
          { all = {"как", "вызвать", "механика"} },
          { token = "эвакуатор" },
          { all = {"вызвать", "механиков"} },
          { all = {"позвать", "механика"} },
          { all = {"заправить", "автобус", "механик"} },
          { all = {"позвонить", "механик", "заправ"} },
        },
      },
      exclusions = {
        {all = { "квест", "механик" } },
        {all = { "заклад" } },
        {all = { "участк" }, none = { "090" } },
      },
    },
    {
      id = "faq.gameplay.fix",
      context = "faq",
      category = "gameplay",
      label = "Ремкомплект /fix",
      enabled = true,
      action = { type = "reply", text = "/fix" },
      triggers = {
        any = {
          { token = "ремкомплект" },
          { all = {"рем", "комплект"} },
          { all = {"как", "ремкомплект"} },
          { all = {"воспользоваться", "рем"} },
          { all = {"repair", "kit"} },
          { all = {"как", "починить", "машину"} },
          { all = {"починить", "авто"} },
          { all = {"поченить", "машину"} },
        },
      },
    },
    {
      id = "faq.gameplay.unrent",
      context = "faq",
      category = "gameplay",
      label = "Аренда транспорта",
      enabled = true,
      action = { type = "reply", text = "/unrent" },
      triggers = {
        any = {
          { all = {"арендовал", "скутер"} },
          { all = {"аренда", "транспорт"} },
          { token = "unrent" },
          { all = {"на", "крыше", "заспавн"} },
          { token = "арендован" },
        },
      },
    },
    {
      id = "faq.gameplay.bp",
      context = "faq",
      category = "gameplay",
      label = "Батл Пасс /bp",
      enabled = true,
      action = { type = "reply", text = "/bp" },
      triggers = {
        any = {
          { all = {"батл", "пасс"} },
          { all = {"battle", "pass"} },
          { all = {"баттл", "пасс"} },
          { token = "/bp" },
          { token = "battlepass" },
        },
      },
      exclusions = {
        { },
        { },
        {all = { "топ", "батл" } },
        {all = { "квест" }, none = { "бп", "battle", "батл" } },
      },
    },
    {
      id = "faq.gameplay.tasks",
      context = "faq",
      category = "gameplay",
      label = "Прогресс БП /tasks",
      enabled = true,
      action = { type = "reply", text = "/tasks" },
      triggers = {
        any = {
          { all = {"задания", "бп"} },
          { all = {"прогресс", "бп"} },
          { all = {"задания", "bp"} },
          { token = "/tasks" },
          { all = {"ежедневн", "задан"} },
          { all = {"сезонн", "задан"} },
          { all = {"battle", "pass", "задан"} },
          { all = {"задания", "battle"} },
          { all = {"открыть", "задания", "бп"} },
        },
      },
      exclusions = {
        {all = { "квест", "пицц" } },
        {all = { "квест", "автобус" } },
        {all = { "квест", "трамвай" } },
      },
    },
    {
      id = "faq.gameplay.creditshelp",
      context = "faq",
      category = "gameplay",
      label = "Advance Credits — help",
      enabled = true,
      action = { type = "reply", text = "/creditshelp" },
      triggers = {
        any = {
          { all = {"адванс", "кредиты"} },
          { all = {"advance", "credits"} },
          { token = "creditshelp" },
          { all = {"кредиты", "как", "использовать"} },
          { all = {"адванс", "кредит"} },
          { all = {"меню", "кредит"} },
          { all = {"тратить", "адванс"} },
          { all = {"юзать", "кредит"} },
          { all = {"где", "взять", "адванс"} },
          { all = {"как", "адванс", "кредиты", "использовать"} },
        },
      },
      exclusions = {
        {all = { "сколько", "кредит" } },
        {all = { "баланс", "кредит" } },
        { },
        {all = { "кредит" }, none = { "advance", "credits", "donate", "адванс", "credit" } },
      },
    },
    {
      id = "faq.economy.mn_1",
      context = "faq",
      category = "economy",
      label = "Баланс кредитов /mn 1",
      enabled = true,
      action = { type = "reply", text = "/mn 1" },
      triggers = {
        any = {
          { all = {"баланс", "кредит"} },
          { all = {"сколько", "кредит"} },
          { all = {"кредит", "баланс"} },
          { all = {"сколько", "адванс", "кредит"} },
          { all = {"чекнуть", "адванс", "кредит"} },
          { all = {"сколько", "advance", "credits"} },
          { all = {"где", "посмотреть", "койны"} },
        },
      },
    },
    {
      id = "faq.economy.price",
      context = "faq",
      category = "economy",
      label = "Магазины /price",
      enabled = true,
      action = { type = "reply", text = "/price" },
      triggers = {
        any = {
          { token = "/price" },
          { all = {"список", "магаз"} },
          { all = {"магазин", "price"} },
          { token = "пиротехник" },
          { token = "салют" },
          { all = {"24", "7"} },
          { all = {"где", "магазин"} },
          { all = {"магазин", "одежд"} },
          { token = "парикмахер" },
          { all = {"магазин", "мебел"} },
          { all = {"где", "купить", "салют"} },
          { all = {"аксессуар", "магаз"} },
          { all = {"где", "магазины", "24"} },
          { all = {"купить", "еду"} },
          { all = {"купить", "аксессуар"} },
          { all = {"купить", "гитар"} },
        },
      },
      exclusions = {
        {all = { "отель" } },
        {all = { "гостиниц" } },
        {all = { "заселиться" } },
        { },
        { },
      },
    },
    {
      id = "faq.gameplay.price_2",
      context = "faq",
      category = "gameplay",
      label = "Отмычка",
      enabled = true,
      action = { type = "reply", text = "/price магазин игрушек" },
      triggers = {
        any = {
          { token = "отмычк" },
          { all = {"взлом", "машин"} },
          { all = {"купить", "отмыч"} },
          { all = {"где", "отмыч"} },
          { all = {"преобрести", "отмыч"} },
        },
      },
    },
    {
      id = "faq.gameplay.sellsim",
      context = "faq",
      category = "gameplay",
      label = "Продать SIM /sellsim",
      enabled = true,
      action = { type = "reply", text = "/sellsim" },
      triggers = {
        any = {
          { all = {"продать", "сим"} },
          { token = "sellsim" },
          { all = {"симк", "прод"} },
          { all = {"симку", "чел"} },
        },
      },
    },
    {
      id = "faq.gameplay.adlist",
      context = "faq",
      category = "gameplay",
      label = "Адвокат /adlist",
      enabled = true,
      action = { type = "reply", text = "/adlist" },
      triggers = {
        any = {
          { all = {"вызвать", "адвокат"} },
          { all = {"адвокат", "номер"} },
          { token = "adlist" },
          { all = {"список", "адвокат"} },
          { all = {"как", "адвокат"} },
          { all = {"визвать", "адвокат"} },
          { all = {"адвоката", "в", "тюрьму"} },
        },
      },
    },
    {
      id = "faq.gameplay.free_id",
      context = "faq",
      category = "gameplay",
      label = "Выпустить из тюрьмы /free",
      enabled = true,
      action = { type = "reply", text = "/free id" },
      triggers = {
        any = {
          { all = {"выпустить", "тюрьм"} },
          { all = {"выпустить", "адвокат"} },
          { all = {"как", "выпустить", "из", "тюрьмы"} },
          { all = {"из", "тюрьмы", "адвокат"} },
        },
      },
    },
    {
      id = "faq.gameplay.setspawn",
      context = "faq",
      category = "gameplay",
      label = "Спавн точка /setspawn",
      enabled = true,
      action = { type = "reply", text = "/setspawn" },
      triggers = {
        any = {
          { all = {"место", "спавна"} },
          { token = "setspawn" },
          { all = {"сменить", "спавн"} },
          { all = {"поменять", "спавн"} },
          { all = {"спавн", "орга"} },
          { all = {"изменить", "спавн"} },
          { all = {"точка", "спавна"} },
          { all = {"как", "выбрать", "спавн"} },
          { all = {"выбрать", "место", "спауна"} },
        },
      },
    },
    {
      id = "faq.gameplay.ad",
      context = "faq",
      category = "gameplay",
      label = "Подать объявление /ad",
      enabled = true,
      action = { type = "reply", text = "/ad" },
      triggers = {
        any = {
          { all = {"как", "подать", "объявление"} },
          { all = {"подать", "объявление"} },
          { token = "/ad" },
          { all = {"объявление", "команда"} },
          { token = "объявление" },
          { token = "обьявление" },
          { all = {"как", "обьявление", "подать"} },
          { all = {"ad", "команда"} },
          { all = {"купить", "инфернус", "объявлен"} },
        },
      },
      exclusions = {
        {all = { "номер", "телефон" } },
        {all = { "мой", "номер" } },
        {all = { "аксессуар" } },
        {all = { "гитар" } },
      },
    },
    {
      id = "faq.communication.c",
      context = "faq",
      category = "communication",
      label = "Позвонить /c",
      enabled = true,
      action = { type = "reply", text = "/c" },
      triggers = {
        any = {
          { all = {"как", "позвонить"} },
          { all = {"позвонить", "игроку"} },
          { all = {"как", "звонить"} },
          { all = {"говорить", "телефон"} },
          { all = {"как", "разговаривать"} },
          { all = {"звонить", "с", "мобилки"} },
          { all = {"позвонить", "телефоне"} },
        },
      },
      exclusions = {
        {all = { "купить", "телефон" } },
        {all = { "мой", "номер" } },
        {all = { "узнать", "номер" } },
      },
    },
    {
      id = "faq.communication.price",
      context = "faq",
      category = "communication",
      label = "Купить телефон",
      enabled = true,
      action = { type = "reply", text = "/price" },
      triggers = {
        any = {
          { all = {"купить", "телефон"} },
          { all = {"телефон", "где"} },
          { all = {"где", "телефон"} },
          { all = {"нет", "телефона"} },
        },
      },
      exclusions = {
        {all = { "квест", "телефон" } },
      },
    },
    {
      id = "faq.gameplay.f2_f9",
      context = "faq",
      category = "gameplay",
      label = "Микрофон (войс)",
      enabled = true,
      action = { type = "reply", text = "F2; настройки F9" },
      triggers = {
        any = {
          { all = {"включить", "микрофон"} },
          { all = {"войс", "чат"} },
          { all = {"микрофон", "как"} },
          { all = {"f2", "микро"} },
          { all = {"voice", "chat"} },
          { all = {"не", "работает", "микро"} },
          { all = {"войсом", "пользов"} },
          { all = {"голосовой", "чат"} },
          { all = {"как", "говорить", "войс"} },
          { all = {"забиндить", "войс"} },
          { all = {"клавиша", "войс"} },
          { all = {"как", "говорить", "в", "микро"} },
          { all = {"голосовой", "как"} },
        },
      },
    },
    {
      id = "faq.gameplay.warninfo",
      context = "faq",
      category = "gameplay",
      label = "Варн инфо /warninfo",
      enabled = true,
      action = { type = "reply", text = "/warninfo" },
      triggers = {
        any = {
          { all = {"сколько", "варнов"} },
          { all = {"мои", "варны"} },
          { token = "warninfo" },
          { all = {"варн", "инфо"} },
          { all = {"срок", "варна"} },
        },
      },
    },
    {
      id = "faq.gameplay.lic",
      context = "faq",
      category = "gameplay",
      label = "Лицензии /lic",
      enabled = true,
      action = { type = "reply", text = "/lic" },
      triggers = {
        any = {
          { all = {"показать", "лицензии"} },
          { all = {"мои", "лицензии"} },
          { token = "/lic" },
          { all = {"лицензии", "команда"} },
          { all = {"как", "показать", "лиц"} },
          { token = "lic" },
          { all = {"лицензия", "показать"} },
        },
      },
      exclusions = {
        {all = { "купить", "лиценз" } },
        {all = { "получить", "лиценз" } },
        {all = { "список", "лицензер" } },
      },
    },
    {
      id = "faq.gameplay.gps_5_1",
      context = "faq",
      category = "gameplay",
      label = "Квест трамвай",
      enabled = true,
      action = { type = "reply", text = "/gps 5, проедь 1 круг" },
      triggers = {
        any = {
          { all = {"квест", "трамвай"} },
          { all = {"трамвай", "квест"} },
          { all = {"квест", "трамвае"} },
          { all = {"как", "сделать", "трамвай"} },
          { all = {"трамвайный", "квест"} },
        },
      },
    },
    {
      id = "faq.gameplay.buym",
      context = "faq",
      category = "gameplay",
      label = "Загрузить металл /buym",
      enabled = true,
      action = { type = "reply", text = "/buym" },
      triggers = {
        any = {
          { all = {"загрузить", "металл"} },
          { all = {"металл", "в", "грузовик"} },
          { all = {"как", "загрузить", "руду"} },
          { token = "buym" },
          { all = {"металл", "куда"} },
        },
      },
    },
    {
      id = "faq.navigation.gps_5",
      context = "faq",
      category = "navigation",
      label = "GPS Шахта",
      enabled = true,
      action = { type = "reply", text = "Шахта: /gps 5" },
      triggers = {
        any = {
          { all = {"шахта", "квест"} },
          { all = {"где", "шахта"} },
          { all = {"шахта", "где"} },
          { all = {"шахта", "gps"} },
          { all = {"металл", "набрать"} },
          { all = {"где", "металл", "для", "доставки"} },
        },
      },
      exclusions = {
        {all = { "сдать", "металл" } },
        { },
      },
    },
    {
      id = "faq.gameplay.price_22",
      context = "faq",
      category = "gameplay",
      label = "Макс. скорость",
      enabled = true,
      action = { type = "reply", text = "/price 22" },
      triggers = {
        any = {
          { all = {"максималка", "85"} },
          { all = {"лимит", "скорост"} },
          { all = {"макс", "скорост"} },
          { all = {"ограничен", "85"} },
          { all = {"скорост", "85"} },
        },
      },
    },
    {
      id = "faq.gameplay.donate",
      context = "faq",
      category = "gameplay",
      label = "Донат /donate",
      enabled = true,
      action = { type = "reply", text = "/donate" },
      triggers = {
        any = {
          { all = {"донат", "команда"} },
          { all = {"пополнить", "донат"} },
          { all = {"донат", "баланс"} },
          { all = {"где", "донат"} },
          { token = "/donate" },
          { all = {"как", "задонатить"} },
          { all = {"как", "использовать", "донат"} },
          { all = {"пополнил", "руб"} },
          { all = {"как", "тратить", "донат"} },
          { all = {"не", "могу", "донат"} },
          { all = {"пополнила", "300"} },
        },
      },
      exclusions = {
        { },
        { },
        { },
      },
    },
    {
      id = "faq.gameplay.leave",
      context = "faq",
      category = "gameplay",
      label = "Покинуть фракцию /leave",
      enabled = true,
      action = { type = "reply", text = "/leave" },
      triggers = {
        any = {
          { all = {"выйти", "из", "орги"} },
          { all = {"уйти", "из", "фракции"} },
          { all = {"выйти", "организа"} },
          { token = "/leave" },
          { all = {"как", "уйти", "из", "банды"} },
          { all = {"выйти", "гос"} },
        },
      },
    },
    {
      id = "faq.communication.2",
      context = "faq",
      category = "communication",
      label = "Режим таксиста",
      enabled = true,
      action = { type = "reply", text = "в меню такси нажмите 2" },
      triggers = {
        any = {
          { all = {"принять", "клиента", "такси"} },
          { all = {"клиент", "такси"} },
          { all = {"режим", "таксист"} },
        },
      },
    },
    {
      id = "faq.gameplay.n62",
      context = "faq",
      category = "gameplay",
      label = "Автовокзал",
      enabled = true,
      action = { type = "reply", text = "на автовокзале" },
      triggers = {
        any = {
          { all = {"стоянка", "автобус"} },
          { token = "автовокзал" },
          { all = {"где", "автобус", "стоян"} },
        },
      },
    },
    {
      id = "faq.gameplay.-1",
      context = "faq",
      category = "gameplay",
      label = "Директор завода",
      enabled = true,
      action = { type = "reply", text = "-1 этаж завода" },
      triggers = {
        any = {
          { all = {"директор", "завод"} },
          { all = {"где", "директор", "завод"} },
        },
      },
    },
    {
      id = "faq.gameplay.alt_enter",
      context = "faq",
      category = "gameplay",
      label = "Полноэкранный режим",
      enabled = true,
      action = { type = "reply", text = "Alt+Enter" },
      triggers = {
        any = {
          { token = "полноэкранный" },
          { all = {"полный", "экран"} },
          { all = {"оконный", "режим"} },
          { all = {"alt", "enter"} },
          { all = {"как", "сделать", "полный", "экран"} },
        },
      },
    },
    {
      id = "faq.navigation.gps_5_2",
      context = "faq",
      category = "navigation",
      label = "GPS Нефтезавод",
      enabled = true,
      action = { type = "reply", text = "/gps 5 нефтезавод" },
      triggers = {
        any = {
          { all = {"топлив", "загруз"} },
          { all = {"загрузить", "топлив"} },
          { all = {"топлив", "завод"} },
          { token = "нефтезавод" },
          { all = {"топлив", "привез"} },
          { all = {"где", "топлив", "загруз"} },
        },
      },
      exclusions = {
        { },
        { },
        { },
        { },
      },
    },
    {
      id = "faq.navigation.gps",
      context = "faq",
      category = "navigation",
      label = "GPS / метки",
      enabled = true,
      action = { type = "reply", text = "/gps" },
      triggers = {
        any = {
          { all = {"убрать", "метку"} },
          { all = {"бесполезн", "метк"} },
          { all = {"метк", "gps"} },
          { all = {"как", "gps"} },
          { all = {"ближайший", "24"} },
          { all = {"ближайший", "где"} },
          { all = {"лишн", "метк"} },
        },
      },
      exclusions = {
        {all = { "тир" } },
      },
    },
    {
      id = "faq.gameplay.w",
      context = "faq",
      category = "gameplay",
      label = "Шептать /w",
      enabled = true,
      action = { type = "reply", text = "/w" },
      triggers = {
        any = {
          { token = "шептать" },
          { token = "шепнуть" },
          { token = "whisper" },
          { token = "/w" },
          { all = {"как", "шептать"} },
          { token = "шепток" },
          { all = {"написать", "шепотом"} },
        },
      },
    },
    {
      id = "faq.communication.car",
      context = "faq",
      category = "communication",
      label = "Припарковать /car",
      enabled = true,
      action = { type = "reply", text = "/car" },
      triggers = {
        any = {
          { token = "припарковать" },
          { token = "/car" },
          { all = {"парковка", "машин"} },
          { all = {"поставить", "машину"} },
          { all = {"припарковать", "машин"} },
          { all = {"парковать", "авто"} },
        },
      },
    },
    {
      id = "faq.gameplay.drugs",
      context = "faq",
      category = "gameplay",
      label = "Нарко /drugs",
      enabled = true,
      action = { type = "reply", text = "/drugs" },
      triggers = {
        any = {
          { token = "нарко" },
          { token = "/drugs" },
          { all = {"команда", "нарко"} },
          { all = {"как", "нарко"} },
          { all = {"drugs", "команда"} },
          { all = {"где", "нарко"} },
          { all = {"как", "юзать", "нарко"} },
        },
      },
      exclusions = {
        {all = { "почему", "нарко" } },
        { },
        { },
        {all = { "после", "нарко" } },
      },
    },
    {
      id = "faq.gameplay.leaders",
      context = "faq",
      category = "gameplay",
      label = "Лидеры /leaders",
      enabled = true,
      action = { type = "reply", text = "/leaders" },
      triggers = {
        any = {
          { token = "лидеры" },
          { token = "/leaders" },
          { token = "leaders" },
          { all = {"кто", "лидер"} },
          { all = {"список", "лидер"} },
          { all = {"где", "лидер"} },
        },
      },
      exclusions = {
        { },
        { },
        { },
      },
    },
    {
      id = "faq.gameplay.fpslimit",
      context = "faq",
      category = "gameplay",
      label = "FPS /fpslimit",
      enabled = true,
      action = { type = "reply", text = "/fpslimit" },
      triggers = {
        any = {
          { token = "fpslimit" },
          { token = "/fpslimit" },
          { all = {"фпс", "лимит"} },
          { all = {"fps", "лимит"} },
          { all = {"ограничить", "фпс"} },
          { all = {"фпс", "огранич"} },
        },
      },
    },
    {
      id = "faq.economy.n72",
      context = "faq",
      category = "economy",
      label = "Обмен донат на кредиты",
      enabled = true,
      action = { type = "reply", text = "только в банкомате" },
      triggers = {
        any = {
          { all = {"обменять", "донат"} },
          { all = {"донат", "кредит"} },
          { all = {"кредит", "донат"} },
          { all = {"донат", "на", "кредит"} },
          { all = {"обмен", "донат"} },
        },
      },
    },
    {
      id = "faq.navigation.gps_1",
      context = "faq",
      category = "navigation",
      label = "Автосалон /gps 1",
      enabled = true,
      action = { type = "reply", text = "/gps 1" },
      triggers = {
        any = {
          { token = "автосалон" },
          { all = {"эконом", "автосалон"} },
          { all = {"автосалон", "эконом"} },
          { all = {"автосалон", "лс"} },
          { all = {"где", "автосалон"} },
          { all = {"салон", "машин"} },
          { all = {"авторынок", "лс"} },
        },
      },
      exclusions = {
        { },
        { },
      },
    },
    {
      id = "faq.gameplay.h",
      context = "faq",
      category = "gameplay",
      label = "Завершить звонок /h",
      enabled = true,
      action = { type = "reply", text = "/h" },
      triggers = {
        any = {
          { all = {"как", "закончить", "звонок"} },
          { all = {"завершить", "звонок"} },
          { all = {"закончить", "разговор"} },
          { all = {"как", "закончить", "разговор"} },
          { all = {"положить", "трубку"} },
        },
      },
    },
    {
      id = "faq.gameplay.sellm",
      context = "faq",
      category = "gameplay",
      label = "Сдать металл /sellm",
      enabled = true,
      action = { type = "reply", text = "/sellm" },
      triggers = {
        any = {
          { all = {"сдать", "металл"} },
          { all = {"где", "сдавать", "металл"} },
          { all = {"куда", "сдать", "металл"} },
          { all = {"продать", "металл", "шахт"} },
        },
      },
    },
    {
      id = "faq.gameplay.fuel",
      context = "faq",
      category = "gameplay",
      label = "Список заправок /fuel",
      enabled = true,
      action = { type = "reply", text = "/fuel" },
      triggers = {
        any = {
          { all = {"список", "заправок"} },
          { all = {"заправки", "цены"} },
          { all = {"где", "заправки"} },
          { all = {"список", "азс", "цены"} },
        },
      },
    },
    {
      id = "faq.gameplay.mn_2",
      context = "faq",
      category = "gameplay",
      label = "Квесты новичка /mn 2",
      enabled = true,
      action = { type = "reply", text = "/mn 2" },
      triggers = {
        any = {
          { all = {"где", "квест"} },
          { all = {"как", "найти", "квест"} },
          { all = {"квест", "новичок"} },
          { all = {"квестовая", "линия"} },
          { all = {"где", "брать", "квест"} },
          { all = {"первый", "квест"} },
        },
      },
      exclusions = {
        { },
        { },
        { },
        { },
        { },
      },
    },
    {
      id = "faq.gameplay.season",
      context = "faq",
      category = "gameplay",
      label = "Топ сезона /season",
      enabled = true,
      action = { type = "reply", text = "/season" },
      triggers = {
        any = {
          { all = {"топ", "батлпасс"} },
          { all = {"топ", "сезон"} },
          { token = "/season" },
          { all = {"рейтинг", "сезон"} },
          { all = {"топ", "бп"} },
        },
      },
    },
    {
      id = "faq.gameplay.gps_8",
      context = "faq",
      category = "gameplay",
      label = "Слет домов / риелтор",
      enabled = true,
      action = { type = "reply", text = "/gps 8 риелторское агентство" },
      triggers = {
        any = {
          { all = {"слет", "домов"} },
          { all = {"где", "смотреть", "слет", "домов"} },
          { all = {"риелторское", "агентство"} },
          { all = {"риелтор", "gps"} },
          { all = {"свободные", "дома", "где"} },
        },
      },
    },
    {
      id = "report.watch",
      context = "report",
      category = "reports",
      label = "Следить",
      enabled = true,
      action = { type = "watch", text = "" },
      triggers = {
        any = {
          { requires_id = true },
        },
      },
    },
  },
}
